### ISSUE TITLE
Smarter Enums

### ISSUE THREAD

**Issue by crener** [dotnet/csharplang#1569]
```
public enum Basic
{
    red,  //value = 0
    green,//value = 1
    blue  //value = 2
}

public enum Advanced
{
    orange,             //value = 0
    red = Basic.red,    //value = 0!!
    green = Basic.green,//value = 1
    blue = Basic.blue   //value = 2
}
```

I found myself in a position where I needed to basically make a superset of an enum. This was fine but when it came to testing the superset was returning the wrong value! After debugging there was a conflict in the new enum because the first value was assigned 0 but one of the values explicitly defined was already using 0. 

Why not have enums check for collisions at compile time or at least give a warning so that collisions are not going to happen. Supersets could simply use a different value so these problems can be avoided.

I do see downsides to this as changing an enum could have a cascading effect on other enums which may cause an enum to have to change one of the generated values which could break serialized versions of said enum.

**Comment by jnm2** [comment]
> I do see downsides to this as changing an enum could have a cascading effect on other enums which may cause an enum to have to change one of the generated values which could break serialized versions of said enum.

Also, if you recompile your code with a newer compiler it would introduce a breaking change.

**Comment by tannergooding** [comment]
You can check this kind of stuff using a customer analyzer, if/when required.

There are plenty of cases where having multiple names for the same value is desirable (such as aliasing) and changing this would definitely be a breaking change.

**Comment by dangi12012** [comment]
Yes this is an already happening discussion. This is widely used by APIs where you have some Enum and then some EnumEx with all Enum and some extra values. 
Would be cool for C#

**Comment by asyncawaitmvvm** [comment]
```
public enum Basic
{
    red,  //value = 0
    green,//value = 1
    blue  //value = 2
}

public enum Advanced : Basic
{
    orange,             //value = 0, such is life
}
```

Solved with code from the future, after the nutty professors stopped holding the feature up.

**Comment by crener** [comment]
Ok but what is the value of `Advanced.red` and what happens when I do `Advanced red = Basic.red` (obviously there is all of that Enum casting that i'm skipping) does the value change from red to orange because they both have the same value of 0?

**Comment by asyncawaitmvvm** [comment]
> Ok but what is the value of Advanced.red and what happens when I do Advanced red = Basic.red (obviously there is all of that Enum casting that i'm skipping) does the value change from red to orange because they both have the same value of 0?

Enums already allow multiple names to have the same value. You can even assign one enum value to the enum value of another type without a cast if they have the same base type.

**Comment by crener** [comment]
> Enums already allow multiple names to have the same value. You can even assign one enum value to the enum value of another type without a cast if they have the same base type.

yes but thats the point, If i wanted to real inheritance I would expect the same value from one type to show up in the other if i case to it hence why `Basic.red` should still show up as `Advanced.red`. If they share the same value (from what I have tested in C# currently) it picks the first matching enum value which in this case could be `Advanced.orange` (and if it's not how do i get `Advanced.orange` without getting `Advanced.red`)
