### ISSUE TITLE
Nullable: Annotating property getters separately from setters

### ISSUE THREAD

**Issue by stephentoub** [dotnet/csharplang#2384]
We need a way to annotate get accessors separately from set accessors.

An example comes from WaitHandle, whose SafeWaitHandle property looks like this:
```C#
public SafeWaitHandle? SafeWaitHandle
{
    get
    {
        if (_waitHandle == null)
        {
            _waitHandle = new SafeWaitHandle(InvalidHandle, false);
        }
        return _waitHandle;
    }
    set
    {
        _waitHandle = value;
    }
}
```
Here `_waitHandle` is a `SafeWaitHandle?` because it's lazily initialized, and for better or worse, the setter allows null to be passed to drop the wait handle, after which getting it will cause it to be recreated.  We need to be able to express the fact that you can do:
```C#
waitHandle.SafeWaitHandle = null;
```
while also not incurring warnings any time you use the getter, e.g.
```C#
waitHandle.SafeWaitHandle.DangerousAddRef(ref success);
```
With the annotations available today, one of the above will warn.

cc: @jaredpar, @MadsTorgersen, @dotnet/nullablefc

**Comment by alrz** [comment]
Perhaps this should work?
```cs
public SafeWaitHandle SafeWaitHandle
{
    get => _waitHandle ??= new SafeWaitHandle(InvalidHandle, false);
    [param: Nullable]
    set => _waitHandle = value;
}
```

**Comment by krwq** [comment]
I have similar example but in my case `getter` can give null but you cannot set null:

```csharp
        public DecoderFallback? Fallback
        {
            get
            {
                return _fallback;
            }

            set
            {
                if (value == null)
                    throw new ArgumentNullException(nameof(value));

                // Can't change fallback if buffer is wrong
                if (_fallbackBuffer != null && _fallbackBuffer.Remaining > 0)
                    throw new ArgumentException(
                      SR.Argument_FallbackBufferNotEmpty, nameof(value));

                _fallback = value;
                _fallbackBuffer = null;
            }
        }
```

the `[param: Nullable]` seems to apply only for params and `Nullable` attribute doesn't seem to be recognized

**Comment by stephentoub** [comment]
Here's a potentially more impactful example: TextWriter.NewLine.  Its getter shouldn't return null, but its setter accepts null and translates that into Environment.NewLine.

**Comment by stephentoub** [comment]
@gafter, @MadsTorgersen, how are we tracking issues like this in csharplang that would have a language impact and should be discussed in LDM for C# 8?

**Comment by stephentoub** [comment]
This was addressed by the addition of nullable attributes.

**Comment by weifenluo** [comment]
Where is the `Nullable` attribute?

**Comment by stephentoub** [comment]
> Where is the Nullable attribute?

The relevant attribute here is System.Diagnostics.CodeAnalysis.NotNull (if your property is annotated as nullable because it can return null but you want to prohibit setting it to null) or System.Diagnostics.CodeAnalysis.AllowNull (if your property is annotated as non-nullable because it won't return null but you want to allow setting it to null).

**Comment by weifenluo** [comment]
I tried `[param: AllowNull]`, it does not work.

```
private string? _dbFieldName;
/// <summary>Gets or sets the field name in database.</summary>
public string DbFieldName
{
    get { return _dbFieldName ?? Name; }
    [param: AllowNull]
    set
    {
        _dbFieldName = value;
    }
}
```
When I set nullabe string to `DbFieldName`, I still get `CS8601: Possible null reference assignment.`

**Comment by stephentoub** [comment]
Just put `[AllowNull]` on the property itself, not on the setter.

**Comment by weifenluo** [comment]
> Just put `[AllowNull]` on the property itself, not on the setter.

This works. Thank you.
