### ISSUE TITLE
Defer constructor

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#2722]
To allow initialization able to call abstract member. I think we should have some syntax to allow defer initialization of constructor

```C#
public abstract class A
{
    public abstract string Name { get; }
    public SomeThing Value;
    public A()
    {
        Console.WriteLine("A");
    }
    defer
    {
        Console.WriteLine("defer A");
        if(!dictionary.TryGetValue(Name,out Value)) // can call abstract property Name
            dictionary[Name] = Value = new SomeThing(Name);
    }
}

public class B : A
{
    public override string Name => name;
    public readonly string name;
    public B(string _name)
    {
        Console.WriteLine("B");
         name = "uniqueString" + _name;
    }
    defer
    {
         Console.WriteLine("defer B");
    }
}

////////////////////////////////////////////////////////////////

new B("TT");
// A
// B
// defer B
// defer A
```

The defer block will be called like a stack. Normal constructor would be called from base to derived. But after finished construction it would invoke defer constructor from the derived back to base. And so the each of the base class can call derived class overridden member here

With this feature we would not need any initialization framework and can use only `new` to orchestrate complex initialization

**Comment by djblack** [comment]
Hi,

I like this idea, I often find myself needing an Initialize() method which is called from the most derived class. However the problem with this is that it precludes deriving another class.

Is there a better way to handle this problem?

David

**Comment by canton7** [comment]
Alternatively, allow the base ctor to be explicitly called at any point in the ctor, as in ruby:

```csharp
public abstract class A
{
    public abstract string Name { get; }
    public SomeThing Value;
    public A()
    {
        if(!dictionary.TryGetValue(Name,out Value)) // can call abstract property Name
            dictionary[Name] = Value = new SomeThing(Name);
    }
}

public class B : A
{
    public override string Name => name;
    public readonly string name;
    public B(string _name)
    {
         name = "uniqueString" + _name;
         base();
    }
}
```

Although I'm not too fond of that either, at least it's a little easier to reason about.

**Comment by yaakov-h** [comment]
I don't think it's neccesary to create a new language construct to enable/support blatant violations of [CA2214](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214-do-not-call-overridable-methods-in-constructors?view=vs-2019).

It would be nice if we could do work before calling the base constructor (as @canton7 illustrated whilst I'm typing this), which IMO would be a vastly more readable approach and require no new syntax nodes.

**Comment by djblack** [comment]
Hi,

Not sure I understand what makes two stage initialization problematic? I can see how mixing the two stages would be confusing and error prone though.

David

**Comment by Thaina** [comment]
@canton7 I have seen that in some issue and I think that was actually dangerous. It cannot guaranteed that the derived will ever call the `base` at all. And it also cannot guarantee that the descendant would not try to look at the member of the base class before calling `base`

And so I completely disagree to `Do work before calling base`

The point is we just actually need a complete initialization at the constructor. And that just involve allowing base class to access the derived class implementation. Which could be done with abstract or virtual. And so we actually need stack traversal. Top to bottom then return from bottom back to top. Like `OnBefore-` and `OnAfter-`. I think that should be what we all need for construction logic

**Comment by canton7** [comment]
> It cannot guaranteed that the derived will ever call the base at all

Obviously for backwards compatibility, you will need to implicitly call `base()` if it wasn't explicitly called. I don't like the fact that sometimes calling `base()` will be implicit and sometimes explicit, but "It cannot guaranteed that the derived will ever call the base at all" cannot ever be true.

Your proposal is just splitting the constructor into two parts. Part of the derived class's constructor will be called before part of the base class's constructor (that is after all the entire point of this proposal). This also does "Do work before calling base" -- you've just fudged the problem by calling part of base's constructor "defer" -- but it's still effectively part of the constructor.

If you disagree with the semantics of my syntax, then by implication you're disagreeing with your own proposal 🤷‍♂ 

------------------------

I still agree with @yaakov-h in that we shouldn't be adding syntax which encourages people to violate common-sense rules. 

If you *really* need this behaviour, you can do it already:

```csharp
public abstract class A
{
    public abstract string Name { get; }
    public SomeThing Value;
    public A()
    {
        Initialize();
        if(!dictionary.TryGetValue(Name,out Value)) // can call abstract property Name
            dictionary[Name] = Value = new SomeThing(Name);
    }
    protected abstract void Initialize();
}

public class B : A
{
    public override string Name => name;
    private string name;
    public B(string _name)
    {
    }

    protected override void Initialize() => name = "uniqueString" + _name;
}
```

**Comment by Thaina** [comment]
> This also does "Do work before calling base"

This is not. That's why I propose this feature

Because the base will _always must be call_ the `before part` before the derive. It just have a defer part that not actually a constructor. It just a promise to call after constructor was finished. So actually there are no code in the derived class that will be ever called before base class constructor. That is the point of this proposal. I was actually try to avoid that `Do work before calling base` to happen

And the rule is still exactly the same. You can't call abstract or virtual member before the derived class are finished construction. It actually your proposal to `Do work before calling base` that actually totally violate this rule, not mine

**Comment by canton7** [comment]
> It just have a defer part that not actually a constructor

You can call it what you want, but it is still effectively part of the constructor, as it's called as part of the construction process.

If you want to make it explicitly not part of the constructor, then do this -- you don't need any special syntax:

```csharp
public abstract class A
{
    public abstract string Name { get; }
    public SomeThing Value;

    protected void Initialize()
    {
        if(!dictionary.TryGetValue(Name,out Value)) // can call abstract property Name
            dictionary[Name] = Value = new SomeThing(Name);
    }
}

public class B : A
{
    public override string Name => name;
    private string name;
    public B(string _name)
    {
        name = "uniqueString" + _name;
        Initialize();
    }
}
```

**Comment by Thaina** [comment]
@canton7  No it's not

```C#
public abstract class A
{
    public abstract string Name { get; }
    public SomeThing Value;

    protected void Initialize()
    {
        if(!dictionary.TryGetValue(Name,out Value)) // can call abstract property Name
            dictionary[Name] = Value = new SomeThing(Name);
    }
}

public class B : A
{
    public override string Name => name;
    private string name;
    public B(string _name)
    {
        name = "uniqueString" + _name;
        Initialize();
    }
}

public class C : B
{
    public override string Name => "CString" + base.Name;
    public C(string _name) : base(_name) { }
}

////

new C("TT"); // Initialize will not call C.Name because it call in B, not in C
```

And also your hack is already what I have did before writing this issue. Which is also cannot guarantee that the derived class will ever call `base.Initialize()`

**Comment by canton7** [comment]
Did you try your own code? [DotNetFiddle](https://dotnetfiddle.net/P6L25q).

> Which is also cannot guarantee that the derived class will ever call base.Initialize()

There are lots of things you can't guarantee. There are many things a programmer can do which will break things. You should set a flag in the base class when it's initialised, and check that before other methods are called, the same as setting a flag when `Dispose()` is called.

**Comment by djblack** [comment]
@canton7 while swapping the functionality of the constructor and second phase works, it is even more difficult to see what is going on...

**Comment by canton7** [comment]
> @canton7 while swapping the functionality of the constructor and second phase works, it is even more difficult to see what is going on...

I'd argue it's about the same level of difficulty. Bear in mind that the OP's suggestion means learning entirely new syntax and remembering how it works (which isn't an easy thing to conceptualise). My suggestion at least uses syntax which already exists and which people are familiar with.

**Comment by Thaina** [comment]
@canton7

> There are lots of things you can't guarantee.

We have a language and compiler to make something could be guarantee man

> Did you try your own code? DotNetFiddle.

If this is already work then it actually should be bug. It means that we actually finished overriding member from the derived class even before it call the constructor of derived class. Which should not happen. This is the actual totally violation of CA2214

**Comment by canton7** [comment]
> If this is already work then it actually should be bug.

I think you have a cross misunderstanding of how that code works. C's constructor does not do anything except call B's constructor. 

You've overridden "Name" to mean `"CString" + base.Name;`. You've effectively defined a method which returns `"CString" + base.Name;` every time it is called. That doesn't need to be set up from C's constructor - it's just an intrinsic part of C.

**Comment by Thaina** [comment]
@canton7 

> C's constructor does not do anything except call B's constructor.

If this sentence is true then we should not have CA2214 at all from the start. We should always have virtual function be called in the constructor directly. Which is not true

It's not about C# contructor do any works, it is the order of operation. Constructor should be called along with other member inline assigning. That's include overriding the abstract and virtual and overridden function. And so if it still calling base class constructor, the derived class should not have initial anythings yet, that' why we can't call abstract member yet and that's the reason of CA2214

**Comment by canton7** [comment]
I think you're very confused about what CAC2214 is. 

The problem arises when:

1. The base class defines an abstract method/property, and calls it from its constructor
2. The derived class defines its own field, and initialises it in the constructor
2. The derived class overrides that abstract method/property and refers to that field

Then the base class's constructor will access the abstract method/property, which will invoke the overridden method/property, which will access a field which hasn't yet been assigned.

This is not the case in your class C above. C does not define any fields, and it does not initialise any fields in its constructor.

**Comment by Thaina** [comment]
@canton7 To elaborate my point you can try this

https://dotnetfiddle.net/UHTg7d

It actually shouldn't be possible to run at all, because that field is still in the state of unassigned

**Comment by canton7** [comment]
Right, *now* you've updated the class C so that it meets the 3 points I described above, which is why you now see the problem.

> It actually shouldn't be possible to run at all, because that field is still in the state of unassigned. It just could be assume as null here

Not true. All fields are initialized to their zero value until they're assigned. There is no "unassigned" state for a field.

**Comment by Thaina** [comment]
@canton7 And that's the point that your idea to avoid my proposal at all cost and hacking around with your `Do work before base class constructor` approach will faced

**Comment by canton7** [comment]
> @canton7 And that's the point that your idea to avoid my proposal at all cost and hacking around with your Do work before base class constructor approach will faced

I have no idea what point you're trying to make now I'm afraid - I've been teaching you things that you apparently didn't know about C#, and that's a point?

My points from earlier still stand:

> There are lots of things you can't guarantee. There are many things a programmer can do which will break things. You could set a flag in the base class when it's initialised, and check that before other methods are called, the same as setting a flag when Dispose() is called.
> 
> You could also easily write an analyzer which checks whether Initialize has been called. You could get that working in a matter of days, rather than waiting a matter of years for a proposal like this to be implemented.

**Comment by Thaina** [comment]
@canton7 I have made this feature proposal because all those issue about order of operation messing around between each level of derived class, especially with your `Do work before base class constructor` approach that are chaos. I post this issue to strictly made the constructor process separate from initialize. And you are trying to avoid my proposal by suggest something that far worst

**Comment by canton7** [comment]
No, I'm trying to:

1. Suggest that you write an analyzer. This will fix your issue in *days* rather than *years*
2. Argue that introducing syntax which is very niche (and will therefore be a surprise to most people who see it), and encourages something which is seen as bad design, is a bad thing

**Comment by Thaina** [comment]
@canton7 

1 - I know it could take year so I propose it right now so that it might be possible someday. I could workaround hacking it with many approach myself already, I am thank you for your trying to help but it not really needed for feature request

2 - If you really do just that then it's fine but no, you just try to introduce any random alternative that are not better, actually worse, to mislead the issue. I am not blaming you but we have long argument because of this reason (not that I think it's bad, just state the situation)

**Comment by canton7** [comment]
> I know it could take year so I propose it right now so that it might be possible someday. I could workaround hacking it with many approach myself already, I am thank you for your trying to help but it not really needed for feature request

I'm only saying the same thing that the language team are probably going to say (based on my experience from other issues).

> If you really do just that then it's fine but no, you just try to introduce any random alternative that are not better, actually worse, to mislead the issue. I am not blaming you but we have long argument because of this reason (not that I think it's bad to have conversation, just state the situation)

I made a few suggestions of ways to solve your problem *today*, without needing language changes. The long discussion was because you apparently didn't understand C#, and I had to teach you a few things. That's fine, but don't blame me for that :)

**Comment by Thaina** [comment]
@canton7 Also, I think the actual bad design is that we need to create factory to initial an object. Instead of making it completely initialized from `new` syntax. That's the main point of this issue. I want to have a process to call initialization logic just after constructor. And I want that integrate in the language itself

**Comment by Thaina** [comment]
@canton7

> I made a few suggestions of ways to solve your problem today, without needing language changes

That's what I said `no you are not just doing that`

This is not `today, without needing language changes`

![image](https://user-images.githubusercontent.com/1042507/63088323-ce556c00-bf7e-11e9-9315-a8a390df20db.png)

**Comment by canton7** [comment]
That's true, I *also* made an alternative suggestion to your proposed syntax. You didn't like it and explained why, and that's fine.

**Comment by PathogenDavid** [comment]
Related: https://github.com/dotnet/csharplang/issues/2335

**Comment by HaloFour** [comment]
This proposal is quite unintuitive.  It makes no sense that a `defer` block in the middle of a class definition has anything to do with construction.  There is an existing, and much clearer, proposal regarding two-phase initialization.  All such proposals will have the same problems in that the runtime imposes rules as to what you can do before invoking the base constructor.

**Comment by djblack** [comment]
@HaloFour agree the naming could be better.

Also the linked discussion seems to be concerned with things happening earlier, rather than after in this proposal.

I see lots of cases of both these cases making things more convoluted than they need to be...

**Comment by Thaina** [comment]
@HaloFour The syntax could be changed but what I propose here is opposite approach. Instead of allow anything to happen before base constructor in derived class. I propose that it should be just something like `OnFinishConstructor` event that propagate back to do some more thing in the base class, not to have the derived class will do something before the base constructor

**Comment by HaloFour** [comment]
@Thaina 

> I propose that it should be just something like `OnFinishConstructor` event that propagate back to do some more thing in the base class, not to have the derived class will do something before the base constructor

I see.  I don't see how that makes much sense.  Why would the base constructor/class want or need to do anything additional after the derived class is instantiated?  And there's absolutely nothing in the language/runtime to actually provide such a facility.  Even if C# added some kind of hook it would be completely ignored by other languages, making it completely unenforceable.

**Comment by Thaina** [comment]
@HaloFour I think it is actually very common that we have some initialize logic after constructor. And for a long times we push it into some kind of factory. For instance, the unity component system that we cannot `new MyComponent()` but need to `gobj.AddComponent<MyComponent>()`. Because it has so many logic that required to run after the class completely finish constructing and available to call abstract member

I just want to move those back into the `new` syntax

**Comment by HaloFour** [comment]
@Thaina 

> I think it is actually very common that we have some initialize logic after constructor. 

Yes, and there are common patterns for achieving this, particularly given that such initialization often happens at some indeterminate time after construction, particularly after some properties are set by the consumer.

And syntax aside, how do you propose that the compiler accomplish this?  There's no facility in the runtime to force a call back into the class at some arbitrary point.  You'd be unable to require that this "initializer" actually gets called by downlevel compilers or from other languages.

For both reasons I don't think that this makes sense as a part of the language.

**Comment by Thaina** [comment]
@HaloFour 

> particularly after some properties are set by the consumer.

I think this is not always the case. And that's exactly the point to run some initialization logic after constructor but before any other kind of input. As for the `AddComponent` example above

> And syntax aside, how do you propose that the compiler accomplish this?

If it only for C# then it maybe achieve by inject method call to defer block into `new` syntax. defer block could be transpiled to hidden virtual method that trigger with `new` of the compiler. But that's right, it could work with only language that add this feature into a `new` keyword

**Comment by HaloFour** [comment]
@Thaina 

> hidden virtual method `Init`

Such a method has to be `public` (or at least as accessible as the type itself or any of its constructors).  So the compiler can't do anything about it being potentially called at any point.  Nor can it really do anything interesting or useful, like set `readonly` fields.

What are the use cases for this?  I can count the number of the times that I've wanted a consumer to call into an `Init` method without having first set a few properties on zero hands.  The only time I've ever found a post-construction init useful is for doing stuff after properties have been set to something, and I honestly can't think of any time I've found that useful outside of UI libraries.

**Comment by Thaina** [comment]
@HaloFour The use case is, instead of having user set a property. We could have abstract member and telling user to implement it

We don't ever know when the user will set the property we expected to. Why we should rely on user input for property before initialize? It is not a way to do. That's why we have factory pattern

As I said I just want to move these pattern back into `new` syntax. So we have only single expression to initial everything, don't need to make a document to tell anyone that "Oh, this class cannot `new` manually, you must use this static method to create it"

**Comment by HaloFour** [comment]
@Thaina 

> The use case is, instead of having user set a property. We could have abstract member and telling user to implement it

That's not a use case.  I want to know what problems you are trying to solve that aren't solved by existing language features.  What's a real-world scenario in which you'd want this particular feature?

> So we have only single expression to initial everything, don't need to make a document to tell anyone that "Oh, this class cannot new manually, you must use this static method to create it"

As you put it, "That's why we have factory pattern".  That's exactly what factory patterns are for, and this proposal doesn't obviate the need for that pattern, especially since it very explicitly can/will only invoke a method immediately after the constructor, which won't help much in the majority of the cases where post-initialization requires state or other actions to happen first.

**Comment by Thaina** [comment]
@HaloFour The problem is, we can't call abstract member that we tell user to do in the constructor

And so user need to do something aside from `new SomeClass()` to initialize it

It so common, too common, in the SDK. To tell user that "After you create this class, you need to call `Initialize()`" once before using it. Or "You can't `new` this class. You must use function `SomeFactory.Create<SomeClass>()` to get it instead" or even some SDK that put a private `Initial()` at every member of the class and tell that "If you derived from this class, please don't forget to put `Initial` function in all method and property"

These all the problem that should be solve if the `new` keyword just could also call `Initial` as the default process. All the `input property` you are very concern about can be just another constructor argument instead of waiting for user to input it later (And we need to tell the API consumer that you need to also set this and this property etc,etc)

All of this are a problem that we cannot have user `new MyObject` then everything finished and ready to use after this line. If you must tell an API consumer to do anything aside from this then it is already the problem

**Comment by theunrepentantgeek** [comment]
There's no prohibition against calling abstract methods from your constructor - here's a [SharpLab Sample](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYwCYgNQB8ACATAIwCwAUBfgMwAEAhsAM5yL0DGctRtAgqgEsAtvQA2FAN4VaM7nXzEADLQBy9IQFNaE2gHMNcANy0ADogD2cDZw0ZaTA8YC+02a5k0+gkaIAUASndtINlVdS0AXloAEQ0AM3pkUTg1TQDDIJdyUKDPBWUASVRWcwDaCIA+WgASACIACQ1RUXMYWgKAciFtVI0nWgFUWgAhc0smAEJajOy3WZkzS2srO0YWNk5uJRj4xOTe9IosqnlCWgBhei4QL2ExSVy6S7gyoKl52iycj89n33zaKhwoEPu9QqFeuVAeEZqEvnNQosrDY7OYAG4aRCIAQYLQA2IJJIpcJlSq0WoABWQTCY0yOFAZ5DyZwUAHZgj9CGcweCZGj6IhTNSmFDUBoAO4XK6HD6hBQATl8JmFADoiiUAv5YbzaCFZPzBUIBEx2AALATxUUSqUvWoAWWNZotcVqWr1HmIiqNJvN8TVxQsmu1vMyRyAA=) that shows it works just fine.

What's required for calling of Abstract methods to work is _**Design**_ - and no language keyword is going to supplant that need.

Any base class needs to be designed for subclassing (btw, this is why C# methods are not virtual by default; you have to explicitly opt-in for overriding as a part of your class design). If you design the base class correctly, descendants can override abstract methods and everything works just fine.

As far as I can tell, the mistaken prohibition on calling abstract methods from constructors comes from two sources ...

... developers experienced with C++, where there is indeed such a limitation (at least in some C++ compilers) because the virtual method dispatch table for a type isn't fully initialized until after constructors of the entire hierarchy have executed. C# does not have this limitation, and never has.

... purists who maintain that you shouldn't be calling _any_ of a classes methods until it has been fully initialized. However, from a pragmatic perspective, you can implement the pieces of a class that are needed by the base constructor to work just fine.

If [CA2214](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214-do-not-call-overridable-methods-in-constructors?view=vs-2019) is getting in your way, add `[SuppressMessage()]` to your class declaration with a `Justification=""` and move on.

As an aside ... I've inherited multiple codebases with class hierarchies where `Initialize()` had to be called after construction. In **_every case_**, I was able to refactor the code to completely eliminate the need for consumers to call that method. One useful technique for this was _just in time initialization_ where any deferred initialization was done lazily, just before the result was required.

**Comment by Thaina** [comment]
As long as CA2214 is still active by default I think it should be strictly obeyed. And most people also strictly keep this rule in mind by default too. Because it would always getting in our way by default

There was also a problem that, even you claim that in C# the method table is already initialized. The class itself still not fully construct. The field is not being set and so on as you can see in this fiddle https://github.com/dotnet/csharplang/issues/2722#issuecomment-521582010

And my proposal is not that it would go against CA2214. As I said that this block of code is not actually a constructor. It just like an event that would be triggered on constructor finished. You can think of it as `OnAfterInitialized` that almost all framework and factory was supported

Sure, you can refactor anything or making code injection. But why you need to do it if it could just be language feature?

**Comment by theunrepentantgeek** [comment]
> But why you need to do it if it could just be language feature?

Language features are tremendously expensive; they require design, implementation, testing and (lots) of ongoing maintenance.

I think this question is best turned around the other way ...

Why do you need a language feature when what you want can already be achieved?

The Delphi language introduced a method called `AfterConstruction()` (IIRC) that would automagically be called after all the constructors in the hierarchy are executed. It was a fertile source of bugs.

> The class itself is still not fully constructed.

So? That's a design problem, not a language one. Plus, the problem still exists when your deferred constructor executes, if it calls any other methods on the class.

> As long as CA2214 is still active by default I think it should be strictly obeyed. 

Code Analysis rule sets need to work for you, not the other way around. If you choose can leave the rule active across the entire project and only suppress it where you're sure about your design decisions.

**Comment by Thaina** [comment]
@theunrepentantgeek 

> Language features are tremendously expensive; they require design, implementation, testing and (lots) of ongoing maintenance.

It was a reason to introduce, but not a reason for "why you need to do it if it could just be language feature?"

If it was already be language feature would you still made factory and don't use this language feature?

> Why do you need a language feature when what you want can already be achieved?

- Why you need `using` ? It can be achieved by manually `Dispose`
- Why you need `async`/`await` ? It can be achieved by manually made callback like js `Promise`
- Why you need `foreach` ? It can be achieved by manually `GetEnumerator` and while loop on `MoveNext`
- Why you need constructor and `new`? It can be achieved by `alloc` and manually calling `Init`

**Comment by Thaina** [comment]
@theunrepentantgeek 

> So? That's a design problem, not a language one. Plus, the problem still exists when your deferred constructor executes, if it calls any other methods on the class.

No, because it would be called in back propagated stack. The derived `defer` will be called before base `defer` so the base could expect that the derived is complete

**Comment by yaakov-h** [comment]
@Thaina:
> If it was already be language feature would you still made factory and don't use this language feature?

Honestly, yes. I'd rather reason about two states, "this object is initialized" and "this object is not yet initialized", versus having to deal with figuring out the order of execution of various constructor-related blocks of code and figuring out at what point in the code the object is actually fully ready.

**Comment by Thaina** [comment]
@yaakov-h I think your reasoning is completely reverse

With the current C# constructor. We cannot expect any order of execution and the state of any object. After we call constructor the object may or may not be initialized, may or may not fully ready, may or may not in the state of available to be used

That's the reason I try to propose this feature in the first place; To have an object be completely initialize an object with only one syntax: `new`
And so people don't need to make another creator class, don't need to look for and remember that which object should be create from which class. They could use only `new` for everything. And the object will be `actually fully ready` after the line of `new ThatClass()`

And the one who need to do work about learning this syntax and `figuring out at what point in the code` will be API creator that know everything about their API, not a consumer that just want to `new SomeThing()` and then use it

**Comment by HaloFour** [comment]
@Thaina 

> That's the reason I try to propose this feature in the first place; To have an object be completely initialize an object with only one syntax

But only in those circumstances where "initialization" happens immediately after construction without being able to call other methods or set other properties prior to this "initialization".  In other words, never.  Every single use case of post-constructor initialization I've ever seen within the .NET Framework involved at least setting other properties first, and this language feature would be completely useless there.

I've yet to see a single actual use case of where this feature would be useful.  It seems, at best, to be a language-level way of plastering over bad class design.  If this "initialization" happens immediately post-construction I posit that the "initialization" doesn't need to happen at all and could easily be refactored away.  If this "initialization" requires multiple steps post-construction, that's why the factory pattern exists.

**Comment by Thaina** [comment]
@HaloFour I still don't understand why you still insisting on `able to call other methods or set other properties prior to this initialization`

The point is, why you require the API consumer to set property, instead of explicitly state what arguments you need in the constructor?

Instead of telling that "Hey, after you new this object, you also need to set this property and call this method and then call initialize. You must do it before using my object". I think the API creator should put those require input for initialize in the constructor argument directly

```C#
// Hey, to use MyObject you need to do it like this
var obj = new MyObject(someArgs);
obj.SomeProperty = valueA;
obj.SomeMethod(valueB);
obj.Initialize();
```

No it shouldn't be like this. If my feature is available I will do it like this

```C#
public class MyObject
{
    public MyObject(Argument arg,Value? valueForSomeProperty = null,Value? valueForSomeMethod = null)
    {
        // do something with args
    }
    defer
    {
        if(valueForSomeProperty != null)
            SomeProperty = valueA.Value;

        if(valueForSomeMethod != null)
            SomeMethod(valueForSomeMethod.Value);

        Initialize();
    }
}

////////////////////////////////////////////////////////////////
// Hey, to use MyObject you can just new it
var obj0 = new MyObject(someArgs);

// If you want to set SomeProperty
var obj1 = new MyObject(someArgs,valueA);

// If you want to set SomeProperty and call SomeMethod too
var obj2 = new MyObject(someArgs,valueA,valueA);
```

Or if you really require that user should have freedom to call more complex logic before Initial then I would do it like this


```C#
public class MyObject
{
    public MyObject(Argument arg,Action<MyObject> onBeforeInitial)
    {
        // do something with args
    }
    defer
    {
        if(valueForSomeProperty != null)
            SomeProperty = valueA.Value;

        if(valueForSomeMethod != null)
            SomeMethod(valueForSomeMethod.Value);
    }
}

////////////////////////////////////////////////////////////////

var obj = new MyObject(someArgs,(self) => {
    self.SomeProperty = valueA;
    self.SomeMethod(valueB);
});
```

**Comment by HaloFour** [comment]
@Thaina 

If you have all of the information you need in the constructor then there is zero reason to have a second-pass initialization at all.

> Instead of telling that "Hey, after you new this object, you also need to set this property and call this method and then call initialize. You must do it before using my object". I think the API creator should put those require input for initialize in the constructor argument directly

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.isupportinitialize?view=netframework-4.8

This pattern already exists and is very prevalent in all of the UI designers.

**Comment by JohnLudlow** [comment]
A little late to the party, but it feels like the request is for an answer to this guidance:

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214-do-not-call-overridable-methods-in-constructors?view=vs-2019

In the previous example, if SomeProperty / SomeMethod are abstract or virtual, you shouldn't call them from the constructor. I think this suggestion is for a way to safely call abstract and virtual things from the constructor by deferring part of the constructor logic until after all constructors in the inheritance tree have been called.

Of course, what to do if other things in the inheritance tree also have a deferred block might need to be discussed.

**Comment by Thaina** [comment]
@HaloFour The first reason is CA2214

That property we need to called might be abstract one or utilize overridable member. And while it pass the argument along to the base class, those overridable member is not properly finish initialized yet. That's the whole point of this issue

And to push it as a pattern, even you have interface `ISupportInitialize` for it, it was not completed by calling with only `new` keyword. It must be pushed into some other mechanism to utilize that interface. Which is still not ideal

If possible I wish that, in the vnext the `new` keyword will changed to also call `BeginInit` and `EndInit` after constructor. But it not possible because it would be breaking change. What I really want is that, the `new` keyword should be able make an object completely initialized, not just constructed

**Comment by HaloFour** [comment]
@Thaina 

That's the purpose of factories.  Trying to hide it behind a constructor is a lot of unnecessary complication for no gain, and as soon as your initialization is _slightly_ more complex you have to completely ditch this proposed solution anyway.  Better to make it a proper factory up front and abstract those details away from the consumer of the type.  Pretending that this is a normal constructor would only cause confusion and break expectations across the .NET ecosystem.

**Comment by Thaina** [comment]
@HaloFour 

> That's the purpose of factories.

https://github.com/dotnet/csharplang/issues/2722#issuecomment-521709640

> As I said I just want to move these pattern back into new syntax. So we have only single expression to initial everything, don't need to make a document to tell anyone that "Oh, this class cannot new manually, you must use this static method to create it"

https://github.com/dotnet/csharplang/issues/2722#issuecomment-521869034

> > That's exactly what factory patterns are for
> 
> The pattern exist because language feature have a flawed so we must train people to use some pattern instead of having language feature about it. OOP used to be a pattern before it become language designed specifically for OOP. Pattern could graduate to become full fledged language feature. And I think Factory is too common to be just pattern anymore. We should consider make language feature for it

This is already looping to the point that you just circumlocution preaching the cult of factory pattern
If we just always use pattern then even C# language itself is not need, as I was pointed out https://github.com/dotnet/csharplang/issues/2722#issuecomment-521887878

> - Why you need `using` ? It can be achieved by manually `Dispose`
> - Why you need `async`/`await` ? It can be achieved by manually made callback like js `Promise`
> - Why you need `foreach` ? It can be achieved by manually `GetEnumerator` and while loop on `MoveNext`
> - Why you need constructor and `new`? It can be achieved by `alloc` and manually calling `Init`

**Comment by theunrepentantgeek** [comment]
I don't see how invoking [CA2214](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214-do-not-call-overridable-methods-in-constructors?view=vs-2019) actually motivates this feature at all.

As soon as the class inheritance graph gets more complicated than simple parent/child, any non-trivial deferred construction logic will inevitably end up needing to call a virtual or abstract method.

Then you're right back in the realm of violating CA2214 because the deferred construction code from a parent class is calling into the child class, and initialization of the child class is incomplete because the deferred constructor hasn't yet completed.

All this feature seems to do is add complexity to the language without meaningfully addressing the underlying issue that motivated the suggestion in the first place.

**Comment by theunrepentantgeek** [comment]
@Thaina, the factory pattern has much more value than simply papering over any percieved deficiencies of constructor syntax. 

Factories can (and often are) far more sophisticated than that - they optimize memory allocation, create different instance types in different circumstances, automatically apply policy (e.g. single instance reuse) and so on.

You wrote:

> This is already looping to the point that you just circumlocution preaching the cult of factory pattern

Inflammatory comments like this demonstrate far more about your lack of understanding than anything else. You don't do yourself any favors - you don't encourage anyone to consider your opinions positively - by resorting to rhetoric like this.

I'm out.

**Comment by HaloFour** [comment]
@Thaina 

> My defer constructor feature is exactly abstract those details away from the consumer of the type by make the constructor be the initialization, all complexity is contained in the constructor.

An abstraction for an incredibly narrow definition of "initialization", one that doesn't even cover the common two-phase initialization patterns established in the .NET ecosystem.  And it's an incredibly leaky abstraction as the initialization methods *must* be at least as accessible at the constructors.

And I've yet to hear an actual use case, I've never seen a class that exhibits such an initialization pattern.

There's no reason to cram this behavior into `new`.  That keyword means something very specific.  It's not an overloadable operator for a very good reason.

**Comment by Thaina** [comment]
@HaloFour 

This should already cover 2-phased initialization


```C#
public class MyObject
{
    public MyObject(Argument arg,Action<MyObject> onBeforeInitial)
    {
        // do something with args
    }
    defer
    {
        onBeforeInitial(this);
        Initialize();
    }
}

////////////////////////////////////////////////////////////////

var obj = new MyObject(someArgs,(self) => {
    self.SomeProperty = valueA;
    self.SomeMethod(valueB);
});
```

And you could support any N-phased initialization


```C#
public class MyObject
{
    public MyObject(Argument arg,Action<MyObject> onBeforePhase1,Action<MyObject>,Action<MyObject> onBeforePhase2,Action<MyObject> onBeforePhase3)
    {
        // do something with args
    }
    defer
    {
        onBeforePhase1(this);
        Phase1();

        onBeforePhase2(this);
        Phase2();

        onBeforePhase3(this);
        Phase2();
    }
}

////////////////////////////////////////////////////////////////

var obj = new MyObject(someArgs,(self) => {
    self.SomeProperty = valueA;
    self.SomeMethod(valueB);
},(self) => {
    // beforephase2
},(self) => {
    // beforephase3
});
```

**Comment by HaloFour** [comment]
@Thaina 

Apart from being terribly convoluted, it doesn't at all work with the established two-phase initialization pattern that .NET has used for the past ~20 years.

**Comment by Thaina** [comment]
@HaloFour I have seen you only preaching that it won't work it need factory but never elaborate how it cannot work

**Comment by Thaina** [comment]
@theunrepentantgeek Sure, but did you think that we make create method to always did all of that?

Most of the time it just because we want to run something before and after constructor. Because when the constructor are running in base class. The derived class are not finished initializing and should not be used. That's the whole reason of CA2214 in any OOP language

But my proposal to add defer is not violate it. Because it just let the base class know that the derived class actually finished construction and ping the base class that you now could do some cleanup work you need. If this violate CA2214 then every `Initialize` `Initial` `Init` function that some SDK provider force people to always call after constructor should count as violating CA2214

**Comment by Thaina** [comment]
And all in all. Pattern exist because it lack language feature to support. And we have old pattern that be replaced by language eventually. Now should be time to replace factory pattern as language feature

**Comment by orthoxerox** [comment]
I find myself agreeing with @Thaina. Patterns like factories and init methods are a sign of the language's incapability of expressing the programmer's intent.

Saying "nah, there's an existing, less clean way of doing what you want" is a very weak rebuttal, because that's true for a lot of features. "This is a very specific solution that doesn't solve most issues with constructors" is a better one.

**Comment by HaloFour** [comment]
>  have seen you only preaching that it won't work it need factory but never elaborate how it cannot work

No, I've been claiming that it's unnecessary, overcomplicated, fragile and doesn't fit with either established standards or the .NET ecosystem.

If the language team was interested in making `new` an abstraction over any arbitrary way you can think of to create an object they would have followed the direction already established by C++ and make `new` an overloadable operator.  But they very explicitly decided to not do that because it hides too many details and is ripe for abuse.  This proposal is tantamount to a very narrow form of `new` overloading and it adds quite a bit of language complexity in the name of solving a problem that isn't and has never been a problem.  Factories are the recommended way to handle this even in the languages that support some flavor of this already, and languages like Rust just forego "constructors" completely favoring static initializer methods instead.

If you don't like CA2214 complaining, turn it off.  That's not a compiler warning or some kind of law, it's only a guideline to help you avoid a potential pitfall in invoking a virtual member from within a constructor.  And no, this proposal does not solve that problem, it only moves the goalposts, as it would be just as dangerous to invoke a virtual method from within the `defer` block of any given constructor because a derived class might require further "deferred initialization" as well.  Right back to square one.

**Comment by nh43de** [comment]
@HaloFour 

> 
> 
> > hidden virtual method `Init`
> 
> Such a method has to be `public` (or at least as accessible as the type itself or any of its constructors). So the compiler can't do anything about it being potentially called at any point. Nor can it really do anything interesting or useful, like set `readonly` fields.
> 
> What are the use cases for this? I can count the number of the times that I've wanted a consumer to call into an `Init` method without having first set a few properties on zero hands. The only time I've ever found a post-construction init useful is for doing stuff after properties have been set to something, and I honestly can't think of any time I've found that useful outside of UI libraries.

Since it's hard to imagine a use case, I will walk you through an example:

I have an observable sequence that passes weather info to subscribers at regular intervals, and starts with the current known weather. 

```
            WeatherInfoObservable = Observable
                    .FromEvent<EvtCallBackHandler<WeatherInfo>, WeatherInfo>(
                        x => WeatherCallBackHandler += x,
                        x => WeatherCallBackHandler -= x)
                    .StartWith(CurrentWeather)
                ;
```

Got it?

Ok great, so now to the consumption part:

I have a abstract class that has an abstract OnNext method that is called every time a new weather update is received from the observable. This makes it easy for me to keep subscriber classes simple and clean. Here's the class:

```
    public abstract class WeatherListenerBase : IDisposable
    {
        protected readonly MyConfig myConfig;

        /// <summary>
        /// Stores the latest weather from the stream locally.
        /// </summary>
        private WeatherInfo _weather;

        /// <summary>
        /// Subscription to the IObservable
        /// </summary>
        private readonly IDisposable mySubscription;

        /// <summary>
        /// Constructor
        /// </summary>
        protected WeatherListenerBase(MyConfig config)
        {
            myConfig = config;

            mySubscription = Global.LocalWeather.WeatherInfoObservable.Subscribe(w =>
            {
                OnNext(w);
                _weather = w;
            });
        }

        protected abstract void OnNext(WeatherInfo newWeather);

        public void Dispose()
        {
            mySubscription.Dispose();
        }
    }
```

So far so good.

Now I have a lights controller, deriving from our abstract class, that reacts to the weather, also based on a date time function that is passed through the constructor.


```
    public class LightsController : WeatherListenerBase
    {
        private readonly Func<DateTime> _dateTimeFunction;

        /// <summary>
        /// Constructor
        /// </summary>
        public LightsController(MyConfig config, Func<DateTime> dateTimeFunction) : base(config)
        {
            _dateTimeFunction = dateTimeFunction;
        }

        protected override void OnNext(WeatherInfo newWeather)
        {
            var myTime = _dateTimeFunction();

            //handle new weather etc.
        }
    }

```

However, if you run the code, it will throw an exception because _dateTimeFunction is null... why? Because it hasn't been initialized yet, and nor has virtually anything else in the derived class. Remember, we subscribed to an observable that begins with an element - `.StartWith(CurrentWeather)` - _so the implemented OnNext method ends up being called in the abstract class constructor_. This is a problem that doesn't have an elegant solution except to somehow defer the subscription in the abstract constructor until derived class construction is complete.

**Comment by HaloFour** [comment]
@nh43de 

I can think of use cases, but those use cases would require very minor refactoring to avoid the virtual call within the constructor that results in the problem.  For instance, your use case would easily be fixed by not taking a direct dependency on the observable data source.  You define the listener as an observer, which it is, and subscribe to it externally.  That not only fixes the virtual call problem but it separates the concerns appropriately making it much easier to test.  And I believe that this is the case with all/most such use cases; requiring incredibly minor refactoring to back out of the design problem that leads to the virtual call within the constructor.

But my bigger concerns lie in how a feature like this could be implemented.  It requires the compiler emitting an accessible method which must be called immediately after construction.  But because that call would be expected to be automatically inserted it creates a false expectation with how this feature would work from other languages or downlevel compilers.  The only way to avoid this would be to `modreq` the constructor and initializer so that they can't be called from other languages or downlevel compilers, but that makes the feature hostile to the greater .NET ecosystem and would almost certainly ensure that the CoreFX team wouldn't consider any API additions that would rely on this feature.

@orthoxerox 

> Patterns like factories and init methods are a sign of the language's incapability of expressing the programmer's intent.

The language provides the building blocks to establish the implement those patterns.  In my opinion this is a very good thing for multiple reasons.  If the language were to build in those patterns you'd end up with opinionated and inflexible implementations.  And as patterns come and go you'd end up with tons of language features representing patterns that are no longer recommended.  I don't think that it's the place of the language to pretend that all of the concerns of, say, the factory pattern, should be something that can be hidden behind a `new` keyword.  C++, in making `new` an overloadable operator, does allow for that, and the C# team took the experience of that when they decided not to allow `new` to be overloadable.

**Comment by canton7** [comment]
> But because that call would be expected to be automatically inserted it creates a false expectation with how this feature would work from other languages or downlevel compilers. 

I think this is a very important point. Gafter made is very clear in e.g. #35 that they will not accept syntax which works perfectly in a newer compiler version, and appears to compile fine but behaves incorrectly at runtime in a previous compiler version.

You've got three moving parts here: the base class, the derived class, and the code which instantiates the derived class. Any combination of those can be compiled with an old compiler which doesn't know about this feature, or a new compiler which does. You need to make sure that for every combination, you either produce code which works correctly at runtime, or which fails to compile.

I can't think of a way to do that.

**Comment by Thaina** [comment]
@HaloFour I think most language could let us implement any pattern in general. In fact pattern was made to be free from specific language. It's not special that a language can implement pattern. But instead, a good language can be written into pattern without having programmer implement the same pattern again and again every project

As I said. all along we have pattern that was replaced by better language feature. And people will use that feature instead of implementing pattern that feature was better at

Sure, not all pattern should become language feature. But some pattern is too common. OOP used to be a pattern for PoC. Some pattern was made outdated by generic and delegate. Why Factory cannot?

If Factory is so useful, that's more of a reason to make it a language feature

> I can think of use cases, but those use cases would require very minor refactoring to avoid the virtual call within the constructor that results in the problem

That is the problem in your thinking itself

The problem is, we actually want to run virtual call after object finish construction. But we want to guarantee that it will get called after constructor, even before the assignment operator, and the API consumer should not forget to do it

The solution is, if consumer try to create that object, they should be a way to trigger the initialize process after constructor but before giving that object to the consumer

But to make a `static T Create` function or factory just making another problem. It just push responsibility to another class. If we need to make `Create` function when thing just get a little more complex, why we have `new` keyword in the first place? We should just have `static Create` function instead of constructor. We could just `malloc` and set everything so we don't need any expectation on constructor and everyone will just use `static Create` in the same manner so any class will have only one way to create, everyone will have only one expectation, there will be no confusion that some class can be `new` but some class must `Create` and some class require factory

**Comment by Thaina** [comment]
@canton7 

> works perfectly in a newer compiler version, and appears to compile fine but behaves incorrectly at runtime in a previous compiler version.

If this `defer` syntax was implemented, it then cannot be compiled in old compiler version. `defer {}` is not valid syntax in current version

**Comment by canton7** [comment]
@Thaina

As I said in my previous post, you need to consider cases where:

1. The base class uses `defer` and we'd compiled with a newer compiler version, but the derived class is compiled with an older compiler version. Will the `defer` in the base class still be called? 
2. The derived class uses `defer` and is compiled with a newer compiler version, but the base class is compiled with an older compiler version. Will the `defer` in the derived class still be called?
3. The base class and derived class use `defer`, but the derived class is instantiated from code compiled using an older compiler version. Will the `defer` still be called then?
4. Other fun combinations, like the base class uses `defer`, the derived class doesn't (and is compiled using an older compiler version), and the derived class is called from code which is compiled with a compiler version which understands `defer`

**Comment by HaloFour** [comment]
@Thaina 

> If this `defer` syntax was implemented, it then cannot be compiled in old compiler version.

It's not the `defer` side that is the problem, it's the fact that the consumer looks like a normal `new` expression.

So let's say you make a class library with one of these classes that has a `defer` constructor in a theoretical C# 9.0.  Someone tries to consume that class from C# 8.0, and it looks like it works fine because it's a normal constructor.  But the C# 8.0 compiler doesn't know anything about deferred constructors, thus it never emits this required call to `Init` (or whatever it might be called).  That contract is now silently broken and the deferred initialization will not happen.

Your only choice would be to mark the constructor with something like `modreq`.  This means that any attempt to use that constructor from another language or downlevel compiler will fail since they won't understand that constructor.  That means that no other language can use deferred constructors without language changes.  It also means that changing an existing constructor to a deferred constructor is a breaking change.  And because such a feature would be hostile towards the larger .NET ecosystem it's pretty much guaranteed that the BCL/CoreFX team would forbid the use of deferred constructors in any of the standard APIs.

**Comment by HaloFour** [comment]
@Thaina 

> That is the problem in your thinking itself

Either that's a thinly veiled insult, or it implies that I need to use more imagination to figure out ways to design myself into such a corner to find the utility of this feature.

> But to make a static `T Create` function or factory just making another problem. It just push responsibility to another class. It destroy encapsulation.

Why does it need to be another class?  A class can have static factory methods to create itself.  That's pretty normal.

> If we need to make `Create` function when thing just get a little more complex, why we have `new` keyword in the first place?

Legacy, mostly.  Rust went with normal static methods instead of special language syntax for constructors.  C++ does let you overload `new` so that you can do arbitrary factory-like things.  C# intentionally did not copy that feature.

There are numerous philosophical differences between constructors and factory methods.  We don't expect constructors to initiate expensive fallible logic, like attempting to connect to a network resource or a database.  That's why `Socket` and `SqlConnection` have separate `Connect` methods.  But it's normal for a factory method to initiate such a connection, at least optionally.  We don't expect a constructor to return a pooled instance, but it's not uncommon for a factory method.

**Comment by Thaina** [comment]
@HaloFour Sorry if it make you felt bad but I don't intend to insulting. What I said is meant, to think that we should refactoring the constructor to make a static method or factory is the problem

**Comment by Thaina** [comment]
@HaloFour

> We don't expect constructors to initiate expensive fallible logic

I think I have seen some people already want `async constructor`. And I have seen you have reply in some issue that; "we should have some syntax to run some code before calling base constructor, to validate argument" or something like that

At first I don't think that constructor should do anything much too. But after some thought I realize that, constructor is always be the first method everyone think about create any object in the code. If the API provider require that object should be completely initialized by any means, the language should allow them to orchestrate constructor for it. Or the language should deprecate constructor. So every class would have the same single entrypoint

I think the design of class like `SQLConnection` is not related to this. It was design that way because we can `Disconnect` and `Reconnect` so the act of connection was separated from constructor. Also there was an api design that make a connection object and disconnect by dispose it too

**Comment by Thaina** [comment]
@HaloFour And also another problem of both the static create method and factory is, it cannot reflect the constructor of derived class

It can't even specify constructor pattern, even if it can (which there was propose for such times as #769 but not much movement) it still restrict that every derived class must implement the same constructor. It then force derived class to not able having new argument it might wanted to. And if you **_refactor_** it to be empty constructor and Init method, then it cannot set any readonly field from constructor argument

If you thought we should just refactoring everything with pattern then it just like we craft everything with PVC and duct tape. Sure you can make anything this way but it's ugly

**Comment by Thaina** [comment]
@HaloFour @canton7 Tuple syntax also cause compiler error in older version too. And I don't see anyone in corefx have any problem with that

And we also could solve the tuple problem by include ValueTuple package

Then how about we make those code injection as package for older version too is it possible??

**Comment by canton7** [comment]
@Thaina NuGet packages can provide types. They can't cause older compiler versions to learn how to compile things differently.

Tuples are different - we use a NuGet package so that you can use tuples with a new compiler but an old framework. The NuGet package doesn't let you use tuples with an old compiler.

**Comment by Thaina** [comment]
@canton7 I think code analysis and injection or ILManipulation on post build can made into package isn't it?

**Comment by canton7** [comment]
@Thaina Think about it. If you've got a base class compiled with a new compiler and you're compiling a derived class with an old compiler, either the old compiler throws an error, in which case there's no assembly for your post build IL rewriter to rewrite, or the old compiler does not throw an error (and just doesn't call `defer`), and there's no indication that people need to install your magic NuGet package.

**Comment by YairHalberstadt** [comment]
@canton7

You could use an obsolete attribute to tell people to use the nuget package, and then suppress the error manually. In theory.

**Comment by Thaina** [comment]
@canton7 I think it just that; If we could made a package for magic compiler extension then we need to have using some type from that magic compiler to make it error that it missing the type from some package (maybe attribute to mark that defer block as a function), so people would go grab that package, which also include the attribute and the code injector

And if it could not then just make it error in old compiler

Anyway I think it would always be the same as how wee handle Tuple

**Comment by yaakov-h** [comment]
With Tuples, the compiler knew exactly how to deal with the syntax, but was missing the underlying core types. Those types could be supplied by a variety of means including the BCL, user code, or referenced assemblies such as a nuget package.

You cannot use a nuget package to fix a binary compatibility breaking change that would be introduced by a new language feature that is inherently incompatible with the calling convention of the old compiler.

(Well, you could use `Microsoft.Net.Compilers`, but nobody on the language team or corefx is going to accept that as a solution.)

**Comment by canton7** [comment]
@Thaina 

> then we need to have using some type in the same assembly as that magic compiler to make it error that it missing the type from some package (maybe attribute to mark that defer block as a function)

It's perfectly legal to reference a type in a different assembly, where that type references some other type which you don't know about. I think? That won't cause the old compiler to error.

**Comment by Thaina** [comment]
@canton7 If it in new version of BCL then shouldn't it be a new compiler?

And if it was old compiler, you shouldn't be able to use BCL, so you need to import the assembly from nuget isn't it?

**Comment by HaloFour** [comment]
IMO this proposal could not emit normal constructors.  That's what gets it into trouble with downlevel compilers.  Instead, if it were to emit static methods and then treat those methods as constructors you could solve the problem of using the feature from downlevel compilers as well as other languages.

```cs
// given:
public class Foo {
    public Foo(string s) {
        Console.WriteLine("Hello");
    } defer {
        Console.WriteLine("World");
    }
}

// the compiler emits:
public class Foo {
    private Foo(string s) {
        Console.WriteLine("Hello");
    }

    public static Func<Foo> Create(string s) {
        var foo = new Foo(s);
        return () => {
            Console.WriteLine("World!");
            return foo;
        };
    }
}
```

To updated compilers this could look like a normal constructor:

```cs
Foo foo = new Foo("bar");
```

But to downlevel compilers they would have to call the static method directly:

```cs
// broken into two lines to show detail
Func<Foo> initializer = Foo.Create("bar");
Foo foo = initializer();
```

I still don't endorse the idea, but this should at least address most of the issues I have with the implementation and avoids the biggest issue which is that by reusing constructors other compilers would silently do the wrong thing.

**Comment by canton7** [comment]
@HaloFour that private ctor won't work if there's a derived class (which, after all, is the point of this feature).

**Comment by Nevynette** [comment]
> The Delphi language introduced a method called `AfterConstruction()` (IIRC) that would automagically be called after all the constructors in the hierarchy are executed. It was a fertile source of bugs.

It was the combination of overriding `TObject.AfterConstruction()` and tossing in the `inherited` keyword in the middle of constructors that made for interesting marathon debug sessions. Not to mention that static (class) methods can be overridden in Delphi and `NewInstance()` is both public and virtual. 

What could possibly go wrong with that?
