### ISSUE TITLE
Please properly support interface where constraints, add support for default interface implementations

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/csharplang#3682]
Given this code is legal:

```c#
public interface Test{ string Something{get;} }
    public static TInterface Resolve<TInterface>(TInterface @interface) where TInterface : Test
    { 
        return default;
    }
```

This code should be also...

```c#
public static TInterface Resolve<TInterface>(TInterface @interface) where TInterface : interface
    { 
    }
```
Results in:
`error CS0501: 'C.Resolve<TInterface>(TInterface)' must declare a body because it is not marked abstract, extern, or partial`

Modifying it slightly to:

```c#
public static TInterface Resolve<TInterface>(TInterface @interface) where TInterface : interface
    { 
        return default;
    }
```

Results in multiple other errors...

1. error CS1031: Type expected
2.error CS1002: ; expected
3.error CS1001: Identifier expected
4.error CS1513: } expected
5.error CS1519: Invalid token 'return' in class, struct, or interface member declaration
6.error CS1022: Type or namespace definition, or end-of-file expected
7.error CS0501: 'C.Resolve<TInterface>(TInterface)' must declare a body because it is not marked abstract, extern, or partial

Then I don't have to have:

```c#
public interface Interface{}
```

Then I also don't probably need `Interface<T>` etc ([See](https://github.com/juliusfriedman/net7mma_core/blob/fd895adbce2f4776eee5695431c7b35eb9c1be78/Common/Structures/Struct.cs)) [I might due to return variance but I might be able to use `out` or `in` also]

More importantly with default interface implementations we may want to have something like

`where T : IDisposble, default(IDisposable)` which would signify that it has to be `IDisposble` and have at least a default implementation.

Something like:

`where T : IDisposble, virtual default(IDisposable)` or `where T : IDisposble, in default(IDisposable)` could signify that the default is overridden.

In the end

`where T : interface` means `T` MUST be an interface.

`where T: struct, interface` means `T` must be a struct which implements one interface

`where T: class, interface` means `T` must be a class which implements one interface

`where T: readonly struct, interface` means `T` must be a `readonly struct` which implements one interface OR a plain `struct` in which the method parameter designated by the generic constraint must be passed by `in` or the compiler should CXXX. 

On returns of `default` for such `interface` constraints designated with `readonly` the compiler should not allocate on the stack or 0 memory and just return what would otherwise be known as `null` in the context of that type. 

`where T: struct, Disposable` is already allowed and would continue to have it's current [sic] semantics

`where T: unmanaged` is already allowed and would continue to have it's current [sic] semantics

## Default implementation constraint possibilities

`virtual`, `in`, `out`, `default(Type)`

`default(Type)` - This would signify that the type implements a default of that interface
`in`, `out`, - This would signify that the type has overridden the default implementation and in what way, directly or derived.
`virtual` - This would `signify` that the type has not overridden and is the default or is an abstract type.

**Comment by juliusfriedman** [comment]
cc @HaloFour, @CyrusNajmabadi, @gafter

**Comment by HaloFour** [comment]
Not sure what you're asking for here.  `interface` is not a valid generic type constraint.

**Comment by juliusfriedman** [comment]
Please read the entire proposal

**Comment by HaloFour** [comment]
I don't see a proposal here.  I'm seeing complaints that code using a non-existing `interface` generic constraint doesn't compile, and that you suggest something about a generic constraint around default implementations.  Neither of which makes much sense to me.

**Comment by juliusfriedman** [comment]
kk, you guys can close at your whim as usual.

**Comment by HaloFour** [comment]
If what you're proposing is new generic type constraints to limit generic arguments to interfaces, or specifically to interfaces with default implementations, that's fine.  I'm not sure that describing how such syntax doesn't compile today contributes to the conversation.  I think we'd want use cases and justifications for such features.  I kind of think there might already be an issue out there at least for an `interface` constraint?  A quick search hasn't found it, though.

**Comment by CyrusNajmabadi** [comment]
I'm really struggling to understand what you are asking.  Can you clarify what you want thsi code to mean:

```c#
public static TInterface Resolve<TInterface>(TInterface @interface) where TInterface : interface
    { 
    }
```

?

1. What are the semantics of it?
2. Why are those semantics desirable?

Thanks.

**Comment by juliusfriedman** [comment]
It should complain about the return type..

You took the unfinished case.

**Comment by CyrusNajmabadi** [comment]
> It should complain about the missing return ..

It's complaining because your code is illegal and cannot be parsed properly.  You raised a request on C# lang for this to be supported.  But for it to be supported you need to explain *what* it means.  i.e. you wrote `where TInterface : interface`.  There is no rule in teh C# grammar that allows for this (nor any semantics defined for it).  The *compiler* (which is different from the *langauge*) is error-ing out appropriately when it hits this.

So, if you want the compiler to support this, you need to explain what it actually means for the language.  I can't guess at your intent as your original post is too vague here.  So it would be great if you coudl clarify things.  Thanks!

**Comment by juliusfriedman** [comment]
What do you want clarified, I believe @HaloFour got it after a 2nd read. Perhaps you can ask him?

**Comment by CyrusNajmabadi** [comment]
> What do you want clarified, 

☝️ https://github.com/dotnet/csharplang/issues/3682#issuecomment-658448192

1. What are the semantics of it?
2. Why are those semantics desirable?

RIght now your complaint seems to be about the compiler not already allowing your syntax and having it error when that happens.  But that's how compilers work.  They error on unsupported thigns.  To support this, we would need to decide what it was we were supporting, which means understanding the semantics.  We then need to decide if those semantics are a good thing for the language.

As you are the one proposing this change, i'm asking you to provide that information.

**Comment by juliusfriedman** [comment]
@CyrusNajmabadi I will put it here cause I will assume your on our mobile.

> 1. It should complain about the missing `return` .. not otherwise
> 2. You took the unfinished case. Look a f3w lin3s down where I added the `return default`...
> 3. Your not looking at the bigger pictur3

**Comment by HaloFour** [comment]
So the problem is that the error isn't clear enough here?

I dislike this game of "find the proposal".  Clearly state your expectations and what change you want to see in the language.

**Comment by juliusfriedman** [comment]
As you precluded I would like a constraint for interfaces what more should I say besides I think that we also need something for default interface implementations and the way they are implemented.

**Comment by HaloFour** [comment]
> As you precluded I would like a constraint for interfaces what more should I say besides I think that we also need something for default interface implementations and the way they are implemented.

Then say this, and state, in detail, what that actually means.  Complaining that illegal syntax doesn't compile isn't a proposal to make that syntax legal, nor does it say anything about what that syntax actually does.

Even after you claimed that I had figured it out I had no idea what you were asking for here.

**Comment by juliusfriedman** [comment]
Well mia culpa. If there is anything else I need to do lmk.

**Comment by theunrepentantgeek** [comment]
@juliusfriedman I'm sure that what you've written makes perfect sense to you.

Unfortunately, those of us reading your proposal *do not* understand what you're asking.

My guess, and it's nothing more than a guess, is that there's a bunch of context and thinking that you haven't yet added to the proposal. 

As @CyrusNajmabadi and @HaloFour have already asked, please add that by editing your original post. You need to be really detailed, precise, and explicit about why you think the compiler error is wrong, what semantics you'd expect from successfully compiled code, and what benefit the wider C# ecosystem would receive.

**Comment by juliusfriedman** [comment]
Should I add that here or in the proposal until we get it where you guys want it?

to use interface would be simply that the underlying T is an interface just like Enum means that the type must be so, the same for struct and the same for class, unmanaged etc.

If you would like to reserve `Interface` for that then I have no objection other than allowing `Interface<in/out T>` and just define `public interface Interface{}` somewhere so the meaning is fixed.

Do I need any supporting reasons? *Besides the compilers lack of support for this CIL supported feature*

**Comment by 333fred** [comment]
> Besides the compilers lack of support for this CIL supported feature

This is not a good reason for C# to support something. C# doesn't support a lot of things that you can represent in IL today, including functions not in types, modules, obtaining function pointers to virtual functions, tail calls... the list goes on. It is not the goal of the C# language to be able to represent any valid CIL.

> Should I add that here or in the proposal until we get it where you guys want it?

What we would like is to be convinced of the _why_. Updating your original post would be a good start: talk not just about the specifics of what an `interface` constraint would do, but also why you want it and why existing solutions do not work. Specific examples are very helpful here.

For me, I'm not really understanding your motivation here. I get that you want to say that a method can only accept type parameters that are interfaces, I just have no idea why that would be useful. What _real_ scenario does this help with? Why should the language design team prioritize this over everything already triaged into the [C# 10 milestone](https://github.com/dotnet/csharplang/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A%2210.0+candidate%22) (31 issues and counting!) Every language feature has a very large cost, from the updating the language itself, the compiler, tools based on the compiler, ensuring that there are no bad effects on the runtime, 3rd parties that understand C# needing to update their tooling... and I'm just not seeing this as something that would offset the cost here. A common metric we use on the language team is that every proposal starts at -100 points, and it has to get to 100 points to be worthwhile. Eric Lippert has a good blog post on the philosophy [here](https://docs.microsoft.com/en-us/archive/blogs/ericgu/minus-100-points).

**Comment by juliusfriedman** [comment]
The motivation is simple, people have interfaces and people have structs. The lowest hanging fruit I see here is that interfaces are basically already supported. now that default implementations are coming into use I think it's ever more important to prioritize that over anything else for when the diamond problems occurs which hopefully it won't/

I have read that blog post I believe.

Thank you for your time and input.

I don't have the energy right now to type of exactly what you what [which is why I gave context] but I will do my best to convince you and the team given a little time.

**Comment by CyrusNajmabadi** [comment]
>  a f3w lin3s down where I added the return default...
> Your not looking at the bigger pictur3

This does not answer either of my questions.

> As you precluded I would like a constraint for interfaces

*Why* would you like that?  *Why* would it be a valuable thing for the language?  Can you provide a compelling *example* to help bring me to your position on this?

> Do I need any supporting reasons?

Yes.  You definitely need more of a reason than that.  We don't just add features to the language "just because".  There has to be a "really really really good reason" to do it.  Even feature that are "ok" but not "really good" get routinely rejected because there is limited time and resources to make changes, and every change makes the language more complex.  So if we're going to do it, it better be for a *great* reason.

**Comment by CyrusNajmabadi** [comment]
> The motivation is simple, people have interfaces and people have structs. The lowest hanging fruit I see here is that interfaces are basically already supported. now that default implementations are coming into use I think it's ever more important to prioritize that over anything else for when the diamond problems occurs which hopefully it won't/

I've read this a few times, and i still don't know what the compelling case is to add this constraint.  Saying "people have interfaces and people have structs" is not an argument as to why this would be a good feature to add. :(

**Comment by juliusfriedman** [comment]
@CyrusNajmabadi you tell me what happens if I declare a:

`public void SomeMethod<T>(T t){}`

I can pass it everything except a ref struct

If I change this slightly to 

``` c#
public interface IF {}
    public struct Test: IF { bool inner; }
    public static void SomeMethod<T>(ref T t)
        where T : IF{}
    public static void M(){
        var t= new Test();
        SomeMethod(ref t);
    }
```

Everything works but I pay the price of a single box.

**Comment by jnm2** [comment]
@juliusfriedman The way you're talking about default interface implementations with the syntax `return default;` makes it sound like you think there is a default class implementing every interface. However, the C# 8 language feature is default interface *method* implementations. That's very different.

**Comment by juliusfriedman** [comment]
I had no intention to have it return anything but existing behavior e.g. `null` not actually create an instance of the interface or otherwise, that is left up to the capable method logic writers [hands](https://stackoverflow.com/questions/10732933/can-i-use-activator-createinstance-with-an-interface).

**Comment by jnm2** [comment]
@juliusfriedman Now I understand even less what you're asking for. By "the capable method logic writers hands" are you talking about the programmer, and saying that these C# language changes would only be useful if you use reflection to find a class implementing the interface? Overall, could you give some concrete motivating examples, things you can't do at all today or that come with specific pain points?

**Comment by juliusfriedman** [comment]
Why are you trying to be so critical, why can't I have `interface, new`

**Comment by HaloFour** [comment]
A constraint on default method implementations makes no sense.  How the interface members are implemented should be completely seamless to the consumer of that interface.  Your ability to invoke that member from within the generic method is not impacted by whether or not the implementation is default, implicit or explicit.  What kind of use cases do you think that such a constraint would be useful?

**Comment by HaloFour** [comment]
> Why are you trying to be so critical, why can't I have `interface, new`

You can't `new` an `interface`.  You've described a set of mutually exclusive constraints.

**Comment by juliusfriedman** [comment]
you can't have interface, struct either eh?

**Comment by HaloFour** [comment]
> Why are you trying to be so critical

The onus is on you to provide use cases and justification.  

> you can't have interface, struct either eh?

Sure you can.  A struct can implement an interface.

**Comment by juliusfriedman** [comment]
> > Why are you trying to be so critical
> 
> The onus is on you to provide use cases and justification.


Definitely but not to defend misunderstanding or critical thinking errors.

> 
> > you can't have interface, struct either eh?
> 
> Sure you can. A struct can implement an interface.

And a struct has a default value.

**Comment by jnm2** [comment]
@juliusfriedman This is not criticism. This is a genuine interest in the motivation. The things you're describing sound like they would require drastic changes to both the language and the runtime. It would clear things up greatly to have some idea of what the practical end goals would be. This is a process that the language team takes every feature suggestion through; yours is no different. Such value has to be evaluated for two reasons: 1) there is no way to tell if a feature is good from a design perspective without keeping the use cases in mind. 2) Even the smallest language change is expensive. The -100 points is commonly referred to.

In principle, what we're asking is: show us the pain, and let the community brainstorm alternatives that don't come with such a high cost.

**Comment by HaloFour** [comment]
@juliusfriedman 

You're giving us a lot of reasons to not want to engage with you at all.  If a feature cannot be justified it will not happen, end of story.  If you don't like being asked questions, don't ask for language changes.  _Every_ proposal ever made by the community and by the team itself will go through a barrage of questioning both to justify the purpose of the change and to nail down the exact specifications.

**Comment by juliusfriedman** [comment]
@HaloFour  cry me a river, I don't care about questions but ask questions don't assert misunderstandings.

**Comment by HaloFour** [comment]
@juliusfriedman 

> And a struct has a default value.

Orthogonal, an `interface` does not have a default value.

> don't assert misunderstandings.

Then stop doing it.  This is quickly approaching abusive territory on your part.

**Comment by juliusfriedman** [comment]
@HaloFour 

Dually noted, summarily overruled.

I am not being intentional and I am perceiving the same from you and others.

**Comment by juliusfriedman** [comment]
> @juliusfriedman Now I understand even less what you're asking for. By "the capable method logic writers hands," are you talking about the programmer? By linking "hands" to an example of locating a class via reflection, are you saying that these C# language changes would only be useful if you use reflection to find a class implementing the interface? Overall, could you give some concrete motivating examples, things you can't do at all today or that come with specific pain points (and note what the pain specifically is)?

What can I do to display this other that what I have already show?

**Comment by jnm2** [comment]
@juliusfriedman I don't see any pain points with existing alternatives mentioned in your proposal or subsequent comments. Can you give us the benefit of the doubt and explain very carefully what an example scenario is that cannot be implemented in C# 8 or that is painful to implement in C# 8? I don't mean syntax; I mean running behavior.

**Comment by juliusfriedman** [comment]
I will try and I apologize if I came across incorrectly:
(This is not an argument for #1148) but it fits nicely.
```c#
using System;
public class C {
    public interface IF {}
    public interface ID : IF, IDisposable {bool Inner{get;}}
    ref struct RS {public bool Inner {get;} public void Dispose(){}}
    struct S : ID{ public bool Inner {get;} public void Dispose(){}}
    public static void Test<T>(ref T t) where T : struct, ID {}
    public void M() {
        S s = default;
        Test(ref s);
        RS rS = default;
        //CS0306//Test(ref rS);
    }
}
```

**Comment by jnm2** [comment]
Okay, now you're still going to need to help us out. I'm struggling on my end to follow the meaning of what I'm seeing. What are these `IF`, `ID`, `RS` types for; what is being accomplished in this example? The empty Test method body is making it especially hard to gain a big-picture view.

My best guess is that you're indicating by the commented line that `ref structs` are not as usable in certain scenarios as regular structs. Is that the pain you're talking about which your suggestion would resolve?

**Comment by jnm2** [comment]
I see in your recent edit the `//CS0701` line. Can you explain why you would want to define `Test<T>` that way? Please be patient. I'm using my full capacity for understanding, such as it is. 🙂

**Comment by juliusfriedman** [comment]
I will join the gitter if you prefer, just lmk it might be easier.

I will try to improve the bodies using some example but I did link to context code... that is written for a general case. Let me know what you have exceptions of from a method body there are so many options..

**Comment by dstarkowski** [comment]
@juliusfriedman 

What would you expect to be accepted types for `T` in

    public static void Test<T>(ref T t) where T : unmanaged, ID, S {}

Since you cannot inherit `S`, the only accepted type would be `S`. Which defeats the purpose of generic and is the reason for it being invalid constraint (CS0701). Or am I missing something?

**Comment by juliusfriedman** [comment]
Let me know if I answered your question with my modifications otherwise I will proceed as required sorry for not getting it.

**Comment by Unknown6656** [comment]
> - Why are you trying to be so critical, why can't I have interface, new
> - you can't have interface, struct either eh?
> - cry me a river, I don't care about questions but ask questions don't assert misunderstandings.

Bois, I'm getting some popcorn for this conversation. Anybody want some? 🍿🍿🍿🍿

------

Sweetened sustenance aside...
@juliusfriedman the reason why your original code won't return the error message you expected is the following:
```csharp
public static TInterface Resolve<TInterface>(TInterface @interface) where TInterface : interface { ... }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//     (1) This will be parsed as a regular method declaration
//                                                                                     ^^^^^^^^^
//                      (2) However, the 'interface'-constrained is unknown to the compiler, ...
//                                                                                     ^^^^^^^^^^^^^^^^^
//                                  (3) ... so it parses 'interface { ... }' as an interface declaration.
```
As the compiler parses an interface declaration (3), it is missing the opening and closing brackets `{` and `}` for your method `Resolve<T>` -- thus complaining of the missing method body.

I agree that the error message is a bit misleading, however I doubt that it can easily be fixed, as the syntax `interface ... { }` is internally registered as a non-terminal which has a higher reduction precedence than the terminal keyword `interface` itself (for obvious reasons).

**Comment by CyrusNajmabadi** [comment]
> I think if you implement #1148 You must implement this. (should)

1. I still don't know what 'this' is. 
2. I don't know how #1148 feeds into this. 
3. I'm still looking for some sorry if simple example or explanation that helps motivate the entire conversation. 

>  You tell me what happens if I declare 

You will call 'SomeMethod' paying a ref to your local variable 't' of type 'Test'...

This example did not provide me any insight on what you are asking for it why it would be a desirable thing.

**Comment by 333fred** [comment]
@Unknown6656 I've hidden your comment as the first part of it does not comply with the .NET Foundation code of conduct. If you edit it to remove the first section, please ping me and I'll unhide it.

**Comment by CyrusNajmabadi** [comment]
> I am not doing anything intentionally and I am perceiving the same from you and others.

I've been asking some very basic questions from the beginning that are all about understanding what you are asking for. I've read all your responses. They have come across as vague and circumspect. You say you are not doing this intentionally, and for now I'll believe you. But please, asking as seriously as possible, provide more information and just answer the questions I've asked. 

Thank you

**Comment by juliusfriedman** [comment]
Is there anything specific I can answer more directly sir?

**Comment by mikernet** [comment]
From the gitter discussion what I gleamed is that his fundamental issue is that he can't new up an interface comprised of only default methods where the compiler auto-generates a class/struct that implements that interface. I explained that it's a one-liner to declare that type that implements the interface and I don't think it makes sense for that to be a thing.

**Comment by mikernet** [comment]
Not to mention, how often do you have interfaces where ALL the methods are defaults and you have no suitable types that implement it that you can return as a default? 

This seems like you're proposing a language feature that will require significant effort to save yourself 1 line of code in 1 application. Either that, or I feel like there is a design issue in your code and you are abusing default interface methods because I can't imagine how common this could be, but like others have noted, you are free to demonstrate a use case where this significantly improves the development experience.

**Comment by IllidanS4** [comment]
Related:
https://github.com/dotnet/csharplang/issues/3597
https://github.com/dotnet/csharplang/issues/3579

**Comment by juliusfriedman** [comment]
> Related:
> #3597
> #3579
> 
> Also to provide my understanding, `where T : interface` and `where T : Interface` for some interface `Interface` are very different. It's not like `where T : enum` vs. `where T : Enum`; an interface is not some special type that all interfaces inherit from, rather it is a specific category of types.
> 
> Now constraints exists to constraint the supplier of the type argument and give you more freedom when using the type (or, in the case of the proposed `ref` constraint, the exact opposite). But what matters that the restrictions that are lifted by the constraint are compile-time.
> 
> For now, I don't know which compile-time restriction can be lifted by an `interface` constraint. There could be runtime restrictions (for example the `DispatchProxy` class), but I think runtime-based restrictions are better checked by a static analyzer.
> 
> As for the second proposal (`where T : IDisposble, in default(IDisposable)`) again the same reason holds, and additionally, I don't see any use for that. If you want to check if a specific method is actually implemented, then it shouldn't have a default implementation, since you obviously don't trust it.

Not even `virtual`?

**Comment by IllidanS4** [comment]
> Not even `virtual`? and again `abstract` is not quite the same thing...

If `where T : IDisposble, virtual default(IDisposable)` means that the methods must be `virtual`, then it's the same thing. There is no purely compile-time situation where the virtualness of a method on a type parameter matters. Even though it would be cool to for example be able to inherit from a type parameter, call its base methods etc., and I would support such a proposal, in which case some sort of this could be justifiable, as of now a thing such as this could be only done at runtime, and runtime operations should have runtime constraints.

When you need a positive `int`, you do `if(i > 0)` without encoding the sign into the declaration of `i`. When you need an interface type, you do `if(typeof(T).IsInterface)` without encoding it into the constraints of `T` as well.

**Comment by Unknown6656** [comment]
> @Unknown6656 I've hidden your comment as the first part of it does not comply with the .NET Foundation code of conduct. If you edit it to remove the first section, please ping me and I'll unhide it.

I want to formally apologize for my behaviour. I was just trying to diffuse the tension ;)
The post in question has been edited.

**Comment by mikernet** [comment]
>it would be cool to for example be able to inherit from a type parameter, call its base methods etc., and I would support such a proposal

This would indeed be awesome. Got my mind going about possibilities.

**Comment by juliusfriedman** [comment]
> > Not even `virtual`? and again `abstract` is not quite the same thing...
> 
> If `where T : IDisposble, virtual default(IDisposable)` means that the methods must be `virtual`, then it's the same thing. There is no purely compile-time situation where the virtualness of a method on a type parameter matters. Even though it would be cool to for example be able to inherit from a type parameter, call its base methods etc., and I would support such a proposal, in which case some sort of this could be justifiable, as of now a thing such as this could be only done at runtime, and runtime operations should have runtime constraints.
> 
> When you need a positive `int`, you do `if(i > 0)` without encoding the sign into the declaration of `i`. When you need an interface type, you do `if(typeof(T).IsInterface)` without encoding it into the constraints of `T` as well.

This is already possible in CIL so I miss your point.

**Comment by IllidanS4** [comment]
> This is already possible in CIL so I miss your point.

As far as I know, inheriting from a type parameter is probably representable in CIL, but the resulting code is invalid. Enlighten me if I am wrong, please.

**Comment by juliusfriedman** [comment]
Have interface as a constraint is allowed just like enum is allowed, I will prepare an example asap.

**Comment by jnm2** [comment]
Having a specific interface as a constraint is allowed, but that's not the same thing as a constraint that disallows non-interface types.

**Comment by juliusfriedman** [comment]
> Having a specific interface as a constraint is allowed, but that's not the same thing as a constraint that disallows non-interface types. CIL can't represent the latter. The enum and delegate constraints are base class constraints. There's no base interface type that all interfaces inherit from that could be specified as a constraint. Then there's the class and struct and new() and unmanaged constraints which are special CIL flags. There's no special CIL flag for interfaces.

Are you essentially saying that an CIL method with the constraint defined as interface would not accept IDisposable?

**Comment by 333fred** [comment]
@juliusfriedman did you try to run that IL? I get this:

```
Unhandled Exception: System.Security.VerificationException: Method <Module>.M: type argument 'Test' violates the constraint of type parameter 'T'.
   at Main()
```
because of the exact error that C# is giving you at compile time. You haven't specified that the `T` can be _any_ interface, only that it must inherit from the interface you just defined named `Interface`. As has been explained, CIL _does not_ have the ability represent the constraint you are talking about today. You can represent a _specific_ interface as a constraint, but not _any_ interface as a constraint.

As I see it, you have two options here:
1. Write an analyzer for this. It actually wouldn't be hard: just define an attribute `InterfaceOnly` that's applicable to generic parameters and error when such a parameter is substituted with a non-interface. Something like this:
```cs
using System;

[AttributeUsage(AttributeTargets.GenericParameter)]
public class InterfaceOnly : Attribute {}
public class C<[InterfaceOnly] T> {}

public class D
{
    public void M()
    {
        C<D> c; // Your analyzer would error here
    }
}
```

2. Come back with a full proposal. Detail how CIL would have to change in order to support this, what the semantics would be, and some actual code examples of a real application this would be useful in. Personally, this part is where I still don't understand the proposal: I have no idea why being able to say "This T will only ever be an interface type" is even remotely useful. I can understand the use with struct types or class types: that actually tells you specific semantics of the type in question. But I just do not see the use for it.

**Comment by Joe4evr** [comment]
> 1. Write an analyzer for this.

And in case he doesn't want to, [I already made a package with an analyzer for exactly this scenario](https://www.nuget.org/packages/JiiLib.Constraints/1.0.0-rc1). 🙃

**Comment by juliusfriedman** [comment]
So in 20 years I can obsolete you analyzer ?

**Comment by juliusfriedman** [comment]
> @juliusfriedman did you try to run that IL? I get this:
> 
> ```
> Unhandled Exception: System.Security.VerificationException: Method <Module>.M: type argument 'Test' violates the constraint of type parameter 'T'.
>    at Main()
> ```
> 
> because of the exact error that C# is giving you at compile time. You haven't specified that the `T` can be _any_ interface, only that it must inherit from the interface you just defined named `Interface`. As has been explained, CIL _does not_ have the ability represent the constraint you are talking about today. You can represent a _specific_ interface as a constraint, but not _any_ interface as a constraint.
> 
> As I see it, you have two options here:
> 
> 1. Write an analyzer for this. It actually wouldn't be hard: just define an attribute `InterfaceOnly` that's applicable to generic parameters and error when such a parameter is substituted with a non-interface. Something like this:
> 
> ```cs
> using System;
> 
> [AttributeUsage(AttributeTargets.GenericParameter)]
> public class InterfaceOnly : Attribute {}
> public class C<[InterfaceOnly] T> {}
> 
> public class D
> {
>     public void M()
>     {
>         C<D> c; // Your analyzer would error here
>     }
> }
> ```
> 
> 1. Come back with a full proposal. Detail how CIL would have to change in order to support this, what the semantics would be, and some actual code examples of a real application this would be useful in. Personally, this part is where I still don't understand the proposal: I have no idea why being able to say "This T will only ever be an interface type" is even remotely useful. I can understand the use with struct types or class types: that actually tells you specific semantics of the type in question. But I just do not see the use for it.

http://tpcg.io/yzO0w2eb

**Comment by 333fred** [comment]
All that link shows is that mono has a bug where it's not verifying contraints correctly. If you attempt to assemble and run that il on the actual framework, it will error, as it should.

**Comment by 333fred** [comment]
In fact, if you add `.class public Foo {}` and a call to `M<Foo>()` from the Main method, that also happily works because mono is apparently not checking type constraints (?!), which is terrifying.

**Comment by juliusfriedman** [comment]
> In fact, if you add `.class public Foo {}` and a call to `M<Foo>()` from the Main method, that also happily works because mono is apparently not checking type constraints (?!), which is terrifying.

Theres a lot you probably don't know even about your own .net core... https://github.com/juliusfriedman/net7mma_core/blob/fd895adbce2f4776eee5695431c7b35eb9c1be78/Concepts/Classes/CommonIntermediateLanguage.cs#L861

**Comment by IllidanS4** [comment]
Per ECMA-335:

> Given appropriate definitions for interfaces `I1` and `I2`, and for class `Base`, the following code 
defines a class `Dict` that has two generic parameters, `K` and `V`, where `K` is constrained to implement both interfaces `I1` and `I2`, and `V` is constrained to derive from class `Base`: 
<code>.class Dict`2<(I1,I2)K, (Base)V> { ... }</code>

There is no interface constraint, only a type constraints, which ensures the type argument must inherit from the type if it is a class, or implement it if it is an interface. And you can always create a class or a value type that implements the interface.

> The VES ensures that both special constraints and type constraints are satisfied. The constraints can be checked as early as when a closed type is constructed, or as late as when a method on the constrained generic type is invoked, a constrained generic method is invoked, a field in a constrained generic type is accessed, or an instance of a constrained generic type is created. 

Providing a type that doesn't satisfy any of the constraints is prevented. If Mono doesn't check that, then it is (I guess) not a proper implementation of the CLI.

**Comment by juliusfriedman** [comment]
> Per ECMA-335:
> 
> > Given appropriate definitions for interfaces `I1` and `I2`, and for class `Base`, the following code
> > defines a class `Dict` that has two generic parameters, `K` and `V`, where `K` is constrained to implement both interfaces `I1` and `I2`, and `V` is constrained to derive from class `Base`:
> > `` .class Dict`2<(I1,I2)K, (Base)V> { ... } ``
> 
> There is no interface constraint, only a type constraints, which ensures the type argument must inherit from the type if it is a class, or implement it if it is an interface. And you can always create a class or a value type that implements the interface.
> 
> > The VES ensures that both special constraints and type constraints are satisfied. The constraints can be checked as early as when a closed type is constructed, or as late as when a method on the constrained generic type is invoked, a constrained generic method is invoked, a field in a constrained generic type is accessed, or an instance of a constrained generic type is created.
> 
> Providing a type that doesn't satisfy any of the constraints is prevented. If Mono doesn't check that, then it is (I guess) not a proper implementation of the CLI.

It ran some of your code faster than .net full and .net core so 📦

**Comment by 333fred** [comment]
> I would not crack on mono so much... it got you where u are today IMHO.
> Theres a lot you probably don't know even about your own .net core... https://github.com/juliusfriedman/net7mma_core/blob/fd895adbce2f4776eee5695431c7b35eb9c1be78/Concepts/Classes/CommonIntermediateLanguage.cs#L861

I'm the guy who implemented calli support in the compiler for function pointers in C# 9. I'm well aware that it exists, and insulting my knowledge is going to get us nowhere. Please remember to follow the code of conduct. 

> It ran some of your code faster than .net full and .net core so 📦

You were quoted for relevant sections of the ecma spec. No one talked about performance, we talked about _correctness_. You claimed that there exists an `interface` constraint in CIL. We have told you that it does not, quoted the spec to you, and shown you where your assumptions are incorrect.

This issue is going nowhere. @juliusfriedman, you are welcome to open a new issue when you have taken the time to write a complete proposal as to what you want, why you want it, and how it would be implemented. Take a look at the proposals folder, there's a lot of good examples there of the levels detail I'm talking about.

**Comment by juliusfriedman** [comment]
> > I would not crack on mono so much... it got you where u are today IMHO.
> > Theres a lot you probably don't know even about your own .net core... https://github.com/juliusfriedman/net7mma_core/blob/fd895adbce2f4776eee5695431c7b35eb9c1be78/Concepts/Classes/CommonIntermediateLanguage.cs#L861
> 
> I'm the guy who implemented calli support in the compiler for function pointers in C# 9. I'm well aware that it exists, and insulting my knowledge is going to get us nowhere. Please remember to follow the code of conduct.
> 


Sorry I couldn't find the API you made available for it, my apolagies.

> > It ran some of your code faster than .net full and .net core so 📦
> 
> You were quoted for relevant sections of the ecma spec. No one talked about performance, we talked about _correctness_. You claimed that there exists an `interface` constraint in CIL. We have told you that it does not, quoted the spec to you, and shown you where your assumptions are incorrect.
> 
> This issue is going nowhere. @juliusfriedman, you are welcome to open a new issue when you have taken the time to write a complete proposal as to what you want, why you want it, and how it would be implemented. Take a look at the proposals folder, there's a lot of good examples there of the levels detail I'm talking about.

```cil
.assembly Hello {}
.assembly extern mscorlib {}



.class interface nested public auto ansi abstract Interface
{
}

.class interface nested public auto ansi abstract Test
{
}

.method public hidebysig static 
    !!T M<class T> () cil managed 
{
    .maxstack 1
    .locals init (
        [0] !!T
    )

    IL_0000: ldloca.s 0
    IL_0002: initobj !!T
    IL_0008: ldloc.0
    IL_0009: ret
}


.method static void Main()
{
    .entrypoint
    .maxstack 1
    call !!0 M<class Interface>()
    pop
    call !!0 M<class Test>()
    pop
    ldstr "Hello, world!"
    call void [mscorlib]System.Console::WriteLine(string)
    ret
}
```

Is also valid and works...

Why not just add the interface `keyword` and build even better semantics around it I don't know... that would be to good.

**Comment by juliusfriedman** [comment]
> > I would not crack on mono so much... it got you where u are today IMHO.
> > Theres a lot you probably don't know even about your own .net core... https://github.com/juliusfriedman/net7mma_core/blob/fd895adbce2f4776eee5695431c7b35eb9c1be78/Concepts/Classes/CommonIntermediateLanguage.cs#L861
> 
> I'm the guy who implemented calli support in the compiler for function pointers in C# 9. I'm well aware that it exists, and insulting my knowledge is going to get us nowhere. Please remember to follow the code of conduct.
> 
> > It ran some of your code faster than .net full and .net core so 📦
> 
> You were quoted for relevant sections of the ecma spec. No one talked about performance, we talked about _correctness_. You claimed that there exists an `interface` constraint in CIL. We have told you that it does not, quoted the spec to you, and shown you where your assumptions are incorrect.
> 
> This issue is going nowhere. @juliusfriedman, you are welcome to open a new issue when you have taken the time to write a complete proposal as to what you want, why you want it, and how it would be implemented. Take a look at the proposals folder, there's a lot of good examples there of the levels detail I'm talking about.

Where is the apir for `calli` for users? I couldn't find that so I apologize...

What assumptions, and this exact same issue appears with less detail as linked to (with my down vote for such)

**Comment by 333fred** [comment]
> Where is the apir for calli for users? I couldn't find that so I apologize...

https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md
