### ISSUE TITLE
Added : C# Language Design Notes for Aug 9, 2017

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/csharplang#822]
[C# Language Design Notes for Aug 9, 2017](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-08-09.md)

We discussed how nullable reference types should work in a number of different situations.

1. Default expressions
2. Array creation
3. Struct fields
4. Unconstrained type parameters

Please discuss!

**Comment by sharwell** [comment]
> Array creation

I would suggest the following:

1. Make the warning ID for `new string[10]` different from the warning reported for other scenarios
2. Make sure no warning is reported for `new string[expr0]`, where `expr0` is a constant expression which evaluates to 0
3. Suggest (as part of the release notes on the feature) that users create an `T[] ArrayCreate<T>(int length, T initialValue)` method which can be used to construct initialized arrays of non-nullable types

> Unconstrained type parameters

The use of default expressions within generic types, at least for all of the cases described in the notes, is covered by the proposal in #727.

**Comment by sharwell** [comment]
> Struct fields

This seems like a good warning.

* Reference types which are values of a struct can be null.
* It's easy to forget this case, leading to bugs.

I would expect warning for using a non-nullable reference type as a field of a struct will have a high rate of detecting potential bugs in the wild.

**Comment by MgSam** [comment]
I disagree with the conclusions about arrays and default expressions. 

If the feature is to be useful, it should not lie to you about the underlying type system. When you create an array, it is always composed of nullable elements. The warnings and type inference should treat it as such. 

How would you even distinguish between an array variable that can be null vs an array variable that can hold nulls but cannot itself be null? 

``` C#
var a = default(string); //This produces a warning? That seems bizarre. 
var a = new int[30]; //The array reference should be non-nullable, but the array elements themselves should always be treated as nullable
```

**Comment by Joe4evr** [comment]
> ```cs
> T? M1<T>(T t) => t;
> var i1 = M1(1); // 'int'
> ```

Yeah, that's about what I was hoping for. 👍 
> If the feature is to be useful, it should not lie to you about the underlying type system.

Like the way that this feature is getting implemented isn't already lying about the type system. 🙃

**Comment by CyrusNajmabadi** [comment]
> If the feature is to be useful, it should not lie to you about the underlying type system

Then we cannot deliver a feature.  After all, the underlying type system *always* can give you nulls.  There is nothing at the CLR level enforcing any of this.  So at best, this is just trying to prevent you from dealing with nulls as long as people are not trying to subvert things.  But it's trivial to subvert any of this (just use a language that doesn't understand/respect these annotations).

Note: this is what other languages do as well (like Kotlin).  And yet, the feature can be useful.  So i reject the claim that for the feature to be useful it must always respect what the underlying type system may do.

**Comment by jnm2** [comment]
@MgSam 
> When you create an array, it is always composed of nullable elements. The warnings and type inference should treat it as such.

But what you're complaining about for array elements is actually what's happening with fields, locals and parameters themselves! They call all hold null at runtime and are not guarded, even though the type system generates best-effort control flow warnings.

I wish an equal amount of effort was going into CLR work to enable strongly-typed non-nullability in a languages.

**Comment by CyrusNajmabadi** [comment]
> The warnings and type inference should treat it as such.

Warnings are inherently just a best effort to tell you that something *may* be a problem.  As such, they will inherently be on a spectrum.  Some people will want to be told about *anything* that could be a problem.  Some people will find that unreasonable and will want something much more gentle. 

For example, i want a way to be able to express that an array contains non-null values.  I will ensure that all the values in it are non-null.  I want to do this so that i don't have to be warned at every point that there may be null when i know that that's not the case.

--

Again, this goes back to the point that compilers can only do very *weak* analysis here.  And if you want to be warned about anything outside that weak analysis, you're going to have a very rough time.

**Comment by CyrusNajmabadi** [comment]
> But what you're complaining about for array elements is actually what's happening with...

Yes.  And that's why we give the user the control to tell us what it means, and we trust it and only want to warn about stuff that seems to go explicitly against that (and even then we give ways to opt out of the warning).

**Comment by MgSam** [comment]
Like many language features, it's all a dial. You can provide really weak guarantees and really weak analysis and make the feature crippled so that even people who might otherwise want to use it won't because its constantly lying to them.

As I've said before, this feature risks *making things worse than they are today*. If I get an NRE from a variable marked as non-nullable, I no longer trust the feature. I stop using it. And not only that, but now I think less of the C# language as well. I go and talk with my colleagues about how they are right that so-so language is less broken and more modern. 

You guys are spending so much time hand wringing over making it easy to upgrade that you risk compromising the much more important use case, the infinite future time after which the feature is delivered. You are already hiding it behind a compiler switch. So make it as effective and honest as it can be once you decide to go and turn that switch on.

**Comment by CyrusNajmabadi** [comment]
> I wish an equal amount of effort was going into CLR work to enable strongly-typed non-nullability in a languages.

Not happening.  And we've seen from other ecosystems that it does not need to happen in order for features like this to be incredibly useful and valuable.  Without those existence proofs i'd be a lot more concerned, but we've seen how this plays out.  

Again, this feature is not about contracts or about 100% foolproof ensuring that no null shall ever be possible.  This feature is about helping catch the vast majority of nulls in the vast majority of cases when people are playing by the rules and not trying to subvert the system.  It's to help prevent nulls from accidentally creeping in by mistake.  

--

To repeat myself from the other thread on this topic: https://github.com/dotnet/csharplang/issues/796#issuecomment-321413032

> I don't know what to tell you :)

> If you want that, it's not happening. Not now at least. Perhaps many years in the future, when we're willing to make an absolutely gargantuan breaking change, or when we're effectively replacing our platform without something entirely new, then things might be different. I fully expect that a future platform would start with non-null as a core concept that would be baked in from the ground up.

> But that isn't being planned, and it's not coming any time soon. As with all our features, we are designing with the ecosystem and community we have, and what would provide that entire group teh largest amount of benefit with the lowest amount of cost and friction. So, in other words, we could have:

> 1. A language and system and ecosystem where null is just not a concept. ETA 15+ years.
> 2. A language and system and ecosystem where null can be mostly stamped out. ETA soon

> We have to be utterly and completely realistic here. :) And we have to be cognizant of the perfect being the enemy of the good. If you want perfect, you're effectively just not going to get it for a long time. But if you're willing ot accept good, you could get something in normal product cycle terms :)

**Comment by CyrusNajmabadi** [comment]
> As I've said before, this feature risks making things worse than they are today. If I get an NRE from a variable marked as non-nullable, I no longer trust the feature. I stop using it. 

This already exists today in other languages, and that hasn't been a problem.  So, overall the *ecosystem* isn't revolting in the way you indicate.  Yes, i *agree* that some users will not use it.  but i don't want to win over 100% of users, i want to be useful to *enough* users.

A good example of this is F#.  You can talk about non-null types in it, but it's not like the compiler actually enforces that completely.  So you can totally get null ref exceptions when you use it.  Is that a problem?  For some users... maybe.  But overall it isn't and people accept that overall it's a great help *even if it isn't perfect*.

**Comment by jnm2** [comment]
> >  wish an equal amount of effort was going into CLR work to enable strongly-typed non-nullability in a languages.
> 
> Not happening. 

Evidently, and yet, I still wish.
I'm certainly willing to settle though. TypeScript has been an almost entirely pleasant experience to the extent that I regularly get jealous. It's all about tradeoffs constrained by back compat, I get it.

**Comment by CyrusNajmabadi** [comment]
> Like many language features, it's all a dial. You can provide really weak guarantees and really weak analysis and make the feature crippled so that even people who might otherwise want to use it won't because its constantly lying to them.

As i've mentioned, we're entirely amenable to actually exposing this as a dial (and it's something we've talked about).  There would be several different types of things users could choose from when turning on the feature.  For example (Again, example example example, not actual design).

1. Enable non-null types.
    a. Warn for dereferences of possibly null values.
    b. Warn for conversions of possibly null values to non-null types.
    c. Warn when creating arrays of non-null values.
    d. etc. etc.

**Comment by CyrusNajmabadi** [comment]
> I'm certainly willing to settle though. TypeScript has been an almost entirely pleasant experience to the extent that I regularly get jealous.

Yup.  And TypeScript has type system holes you can drive a massive truck through.  I've been burned by them myself *while i worked on writing hte TypeScript compiler itself :D *.

Despite that, still a great help :)

**Comment by MgSam** [comment]
Let's stop being theoretical. Arrays should *always* be nullable, here's why.

``` C#
void Main() {
    var a = new Foo[5]; //Compiler infers a is composed of non-nullable elements
    Bar(a[3]); //Bar expects a non-nullable, great! That's just what the compiler thinks we have!
}

void Bar(Foo foo) {
   foo.DoSomething(); //NRE - WTF - foo is supposed to be non-nullable
}
```

If I'm a user and this happens my conclusion is I still have to do defensive null checks everywhere anyway. So then what's the point of the feature? I may as well just use `?.` and `??` and `if(foo == null)` like I'm already doing today.

**Comment by CyrusNajmabadi** [comment]
> Evidently, and yet, I still wish.

Definitely great to wish for.  At some point i'm sure MS will eventually create a fresh platform, using everything we've learned over the decades.  In that platform, i would actually totally expect non-null checking to be baked in.  But we can either do nothing and wait a *looooooooong* time for that to happen, or we can do something that gets us a long way now, while being honest and accepting of the limitations and the ability to be subverted. Again, this is what many other languages have done *including existing .Net languages*, and it's something that works out.

Please let's be pragmatic here.

**Comment by axel-habermaier** [comment]
@CyrusNajmabadi: The only thing that worries me about this entire non-nullness thing is that it is a very high-risk feature that might not work out at all (but that's why it's a good thing you're developing a prototype, maybe that'll convince me of the usefulness of the feature). But I'm afraid that this entire feature is huge, taking a lot of time of the language and compiler teams, which could (maybe better?) also be spent developing feature that are far less controversial and risky with a similarly high impact (e.g., pattern matching, code generators, etc.).

**Comment by jnm2** [comment]
> But I guess you know what you're doing...

This is so quotable. 😁

**Comment by CyrusNajmabadi** [comment]
> //NRE - WTF - foo is supposed to be non-nullable

In our current thinking you would be warned when you create an array of non-null type, but you would still be allowed to create it.  The onus is on you to decide how you want to deal with that warning.

For example, in the above code you could realize that the array is not initialized, and thus the right fix is to convert it to:

```C#
void Main() {
    var a = new Foo?[5]; // Now i've stated that it contains nulls.  No warning here.
    Bar(a[3]); //Bar expects a non-nullable, now i get warned here!
}
```

Or, you could do something like (final design TBD):


```C#
void Main() {
    var a = new Foo[5]!; // I'm suppressing the warning about null values because i know i'm initializing the array next.
    for (int i = 0; i < a.length; i++)
        a[i] = ... SomeNonNullFooValue ...;

    Bar(a[3]); //Bar expects a non-nullable, no warning
}
```

**Comment by orthoxerox** [comment]
I really want to plug as many holes as possible when I flip that switch. I don't care *that* much whether the compile will warn me when an array is created or when it is dereferenced, as long as it does that. What I'm more intrigued about is this:

```c#
T? M1<T>() => default;

var x = M1<string>(); //string?
var y = M2<int>(); //int?
```

**Comment by CyrusNajmabadi** [comment]
@orthoxerox  We're talking about that right now.  

First, it's unclear if we would even allow "T?" as something you could type.  We need to decide if that is allowed (though i think we're going to decide 'yes', it is allowed).  

Second, if we decide it's allowed, we need to state what it means.  Our current belief (which indicates that maybe this syntax isn't great) is that "T?" (where T is unconstrained) means "Values of T can be 'default'".  So, if you have value type, then "T?" is just "T" (as T already implies it can have the default value), whereas if you have a reference type, then "T?" is distinct to T as T implies it cannot have hte default value.

The distinction here is that we're talking about 'default' values, not 'null' values.

**Comment by orthoxerox** [comment]
@CyrusNajmabadi ah, so it will be `int`, not `int?` and will return 0, not null? I understand that's much easier for both the compiler and the CLR to handle, but then the current syntax really does give you the wrong idea, doesn't it?

**Comment by CyrusNajmabadi** [comment]
> but then the current syntax really does give you the wrong idea, doesn't it?

Quite possibly.  That's a definite concern.  We can either:

1.  Disallow this entirely.
2. Accept this, with the syntax specified, and accept the confusion.  Work hard to explain "T?" means "can be default", not "T?" means "can be null".
3. Accept that we want this, but find another syntax.  Something like "T??" :)    Only allowed for unconstrained generics, means very specifically "can be default".  

Too early to make a call.

**Comment by jnm2** [comment]
@CyrusNajmabadi 

There's no chance we could unify these, is there? That would be a dream:

```c#

public static TValue? GetValueOrNull_struct<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key) where TValue : struct

public static TValue? GetValueOrNull_class<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key) where TValue : class
```

**Comment by CyrusNajmabadi** [comment]
@jnm2 Sorry, currently no i don't think.  If you have a proposal on how to get it to work, that would be interesting.

**Comment by jnm2** [comment]
I'd just hate for you to move forward in a way that forever blocked that avenue.

**Comment by MgSam** [comment]
@CyrusNajmabadi Thanks; that sounds much better than silently inferring a non-nullable

**Comment by CyrusNajmabadi** [comment]
>I'd just hate for you to move forward in a way that forever blocked that avenue.

Nothing is ever fully blocked.  i mean, we did nullable value types in C# 2, and it's not blocking us doing this feature now.  :)

**Comment by orthoxerox** [comment]
@CyrusNajmabadi one option would be to generate 2^n methods (where n is the number of unconstrained generic parameters that are adorned with `?`) with constrained parameters behind the scenes and pick one based on the args. Might grow a little hairy when combined with virtual methods, but I can't see a way for such method to infect the caller unless the caller itself is a generic method.

**Comment by eyalsk** [comment]
I'm really looking forward to use the prototype, I hope we will get it sooner than later and I hope that I'll be as excited and that it will be as useful as you guys think. ;)

**Comment by sharwell** [comment]
> Let's stop being theoretical. Arrays should always be nullable, here's why.

@MgSam Here are three signatures which say this is not correct:

```csharp
public static T[] CreateArray<T>(int length, T initialValue);
public static T[] CreateArray<T>(int length, Func<int, T> initialValueFactory);
public static T[] CreateArray<T, TArg>(int length, Func<int, TArg, T> initialValueFactory, TArg argument);
```

Now I agree that inside of `CreateArray` you would need to suppress a warning on the creation of the array, but overall I would not agree with a statement that arrays everywhere should be nullable. Additional edge cases are covered in my first reply to this thread above.

> wish an equal amount of effort was going into CLR work to enable strongly-typed non-nullability in a languages.

@jnm2 This would be unlikely to succeed, since `null` is not inherently bad, and its existence is not even the problem we're trying to solve here. Nullable reference type analysis is an *engineering effort* (i.e. provides objective benefit for a realistic cost, differentiated from the goals of a theoretical/proofs effort) to reduce the number of cases where failure to correctly initialize data results in failure of an application at runtime. Failure to correctly initialize data before use is the true root cause of this class of bugs, and `null` is only one possible representation for the uninitialized data.

I know you aren't personally taking a hard line approach to this implementation, but the distinction I'm making here is very important to understand. Any improvement made against the goals of the engineering effort are taken very seriously, and cost is the most common barrier to adopting alternatives to date that aim to improve theoretical accuracy.

**Comment by jnm2** [comment]
@sharwell 

> This would be unlikely to succeed, since null is not inherently bad, and its existence is not even the problem we're trying to solve here. 

I don't believe I implied that. My views on null as a legitimate part of many domains would disgust @DavidArno. ;-)

> Failure to correctly initialize data before use is the true root cause of this class of bugs, and null is only one possible representation for the uninitialized data.

Yes, and I believe the CLR should make a provision for non-defaultable value types in exactly the same way. I'll see if I can find the conversation here.

**Comment by sharwell** [comment]
> Yes, and I believe the CLR should make a provision for non-defaultable value types in exactly the same way. 

The problem is even more broad than that. The following case uses `null` and suffers from a bug in the same class:

```
private object lazyInitValue;

public object Value => lazyInitValue ?? (lazyInitValue = ExpensiveComputation());

private object ExpensiveComputation()
{
  if (ExpensiveMethod(out var result))
    return result;

  // use defaults
  return null;
}
```

In this case, data was initialized, but it was not *correctly* initialized because the uninitialized value and one of the initialized values are indistinguishable from each other.

**Comment by MgSam** [comment]
@sharwell But methods like that are an exception. Most arrays are not initialized using them. I'd rather the language be designed for the overwhelming majority case (where it's not statically provable that all elements of an array are non-null)

**Comment by CyrusNajmabadi** [comment]
> Most arrays are not initialized using them.

1. I'm not certain that's actually the case.
2. If you don't have an initialized array in your domain, then there's an easy solution, use "Foo?[]".  The purpose here though is to provide a 'true' type for people who, in their domain, know that the array does *not* have nulls in it.

**Comment by MgSam** [comment]
1. In my anecdotal experience, in 10 years of writing C# I've never once seen those methods used. I'd be shocked if a Github search showed something different.
2. The point of the feature is to **catch bugs**. Even if you "know" that your array can't contain nulls, the next guy who maintains the code after you might not "know" that and might modify the code so that some index of the array remains uninitialized. 

Actually, I'm not sure why you're still arguing with me- my biggest area of concern here was the type inference, which you said you'll provide a warning for. I'm fine with non-null arrays being allowed if they're explicitly declared as such.

**Comment by CyrusNajmabadi** [comment]
> the next guy who maintains the code after you might not "know" that and might modify the code so that some index of the array remains uninitialized.

And someone might use reflection to set one of your non-null fields to null.  Or someone might call you from another language that does not respect these method annotations.  etc. etc. 

> he point of the feature is to catch bugs. 

The point is to be able to catch most bugs *while* not being so obnoxious that it can't be used because the analysis is both so weak and the way to convince hte analyzer is so oppressive.  We need to strike a balance here.

**Comment by jnm2** [comment]
@sharwell 

> > Yes, and I believe the CLR should make a provision for non-defaultable value types in exactly the same way.
> 
> The problem is even more broad than that. The following case uses null and suffers from a bug in the same class:

I'm not following why that's relevant. That field should obviously be typed as nullable. What I need from the CLR is a way to make the field non-nullable and also prevent the type from being default-initialized (structs), running a default constructor, or failing to assign to the field in a constructor.


@CyrusNajmabadi 

> And someone might use reflection to set one of your non-null fields to null. 

You're right, but reflection being dangerous isn't a great counterargument. Reflection has always been a loaded gun. It's on you to use it responsibly.

**Comment by sharwell** [comment]
> I'm not following why that's relevant.

My point is that it would be a great deal of work to enforce the behavior, but it still wouldn't catch all the bugs in this category. I haven't seen evidence indicating that the incremental benefit (number of bugs caught by combined CLR+language which are not caught by language alone) is sizable. Also, the thing I'm most interested in is solutions that find bugs even before code executes. The CLR changes might help resolve bugs after they occur, but it's a weaker method of revealing issues.

**Comment by jnm2** [comment]
@sharwell Thanks. What I would reply to that is that CLR changes would enable fully strong typing so that we wouldn't have to rely on flow analysis. We'd have all the safety we currently have using nullable and non-nullable value types, only we wouldn't need a wrapper type. The runtime has been given by the C# team as the reason why we can't strongly type this.

**Comment by jnm2** [comment]
Note on arrays: filling an array of non-nullables with an initial valueis every bit as error-prone as filling it with nulls. Instead of NREs, you'll have a more complex type of bug.

What I would prefer is to only be allowed to create arrays of nullables, populate it, and cast it as an array of non-nullables before returning it. Arrays are already bivariant today and the safety of such a cast is equivalent.

**Comment by sharwell** [comment]
> filling an array of non-nullables with an initial valueis every bit as error-prone as filling it with nulls. Instead of NREs, you'll have a more complex type of bug.

This applies primarily if you are filling it with a non-null value used to indicate "uninitialized". It's specifically intended to handle cases where you want to create an array of non-null values, all in one location, and don't want to use the `!` operator.

💭 Interestingly enough, the entire non-null reference types feature loses a lot of value for code bases that use sentinel objects instead of null to represent uninitialized data.

**Comment by bondsbw** [comment]
Are we past the point-of-no-return with the `T!` syntax?

```c#
// All are true
default(string?) == null
default(string) == null  // warning if opted-in
default(string!) == ""
```
Though I'm not sure how to extract the third default in general from class types, unless the type were constrained with `new ()`.  Which `String` isn't anyway, so it would need to be updated even to allow this syntax.

**Comment by CyrusNajmabadi** [comment]
> Are we past the point-of-no-return with the T! syntax?

We are completely in teh design phase right now.  Absolutely nothing is set.

**Comment by CyrusNajmabadi** [comment]
> You're right, but reflection being dangerous isn't a great counterargument. 

Fine.  Then use the simple argument of: you may be called from C# 7 code, which has no idea about your annotations and may happily pass you null.

**Comment by CyrusNajmabadi** [comment]
> As the owner of a type, what I need from the CLR and language together is a way to make the field non-nullable and also prevent the type from being default-initialized

Nothing will be coming from the CLR currently in this space any time soon.  So let's just put that to rest and focus on what we can actually accomplish from teh language+analyzers approach.

**Comment by yaakov-h** [comment]
Since we're still going the warnings route and not the runtime route... (I'm disappointed but I understand why)

* I'd love it if `default(T)` could produce a valid `T` instead of `null`, but this changes meaning for backwards compatibility. The next-best thing would be `default(T!)` as @bondsbw suggested above. This could then opt into new behaviour, so if a type does not implement some kind of `op_Default` special method (feel free to use that name, or not to), the compiler could emit a "hey that type does not have a non-null default method" warning or error. Probably error.

* I think we need some disambiguation between "nullable array", "array of nullables" and "nullable array of nullables". This crosses into C's `const` nightmare territory, but since array expression are clearly "type-leftsquare-rightsquare" and nullables are "type-questionmark", we could solve this with `string[]?`, `string?[]` and `string?[]?` respectively. I think this would solve some of the confusion above about how we deal with arrays etc.

* Following on from the above, `new string[10]` would always produce a warning, however we could (probably!) safely assume that the developer will quickly fill the array. On the other hand, `new string[] { "foo", "bar", "baz" }` and `new string[0]` are both guaranteed to be non-null and guaranteed to not contain null values. These should not emit warnings.

* Regarding structs, I'd think it should maybe be an error for a struct to contain a non-nullable field or property. Object initialization is (usually 😄) guaranteed to pass through a constructor which controls the object initialization, but structs have no such guarantee and can easily be initialized to zeroed memory, i.e. null for objects, accidentally or on purpose.

**Comment by ufcpp** [comment]
For struct fields, I really want https://github.com/dotnet/csharplang/issues/146.

In analogy with ref-like and blittable structs:

- ref-like: A struct which contains by-ref fields should be treated equally with by-ref type. It's stack-only.
- blittable: A struct which contains blittable fields should be treated equally with blittable primitives. It's unmanaged.
- non-nullable class-like?: A struct which contains non-nullable fields should be treated equally with non-nullable classes. It's non-defaultable.

**Comment by svick** [comment]
@CyrusNajmabadi 

> Accept that we want this, but find another syntax. Something like "T??" :) Only allowed for unconstrained generics, means very specifically "can be default".

I think this is the best option, using `T?` for this would be too confusing.

And the `T??` syntax might not be as bad as it might look at first sight. Consider that in C++ `T&&` does not mean "reference to reference", but "a different kind of reference". Similarly, in C# `T??` would not mean "nullable of nullable", but roughly "a different kind of nullable".

**Comment by DavidArno** [comment]
@sharwell,
> This would be unlikely to succeed, since `null` is not inherently bad, and its existence is not even the problem we're trying to solve here.

Think I've mentioned this before, but for the record, I strongly disagree with both these statements. 

* `null` is inherently bad. [Tony Hoare, the "inventor of `null`"](https://en.wikipedia.org/wiki/Tony_Hoare) quite rightly describes it as a "billion dollar mistake" when he apologised for inventing it.
* And protecting against `null` is exactly the point of this feature. Whilst it will be limited in how much protection it can offer, it's still a step in the right direction, by making non-nullable the default for types.

@CyrusNajmabadi,

To be clear, this feature will always be a bit of kludge. As these meeting notes show, there are inherent problems with the solution, especially around arrays and generics. Your comparisons to F# are slightly disingenuous too in my view. Sure, you can introduce `null` into F#, but it's hard to do so. This won't be the case with C# though, where using `null` is strongly embedded in the language. I remain highly sceptical therefore that this solution will be good enough, just because similar solutions in very different languages have proven good enough.

I think it a great shame that the team seem unwilling to even discuss the idea of non-zero default values, including non-null default references. The CLR is being changed to allow methods to be defined in interfaces. Therefore, now would be an excellent time to experiment with blitting bit patterns (including addresses) as an initialisation method, to see what the performance impact would be. This solution would solve **all** of the issues being discussed here in one stroke.

But the decision is made and so we have what we have. To that end, it is clear to me that statements like `default(string)` and `new string[10]` are inherently meaningless statements that the compiler should warn on. Arrays should be restricted to nullable references. If you want an array, declare it `new string?[10]`. If you want a non-nullable collection, don't use arrays.

**Comment by svick** [comment]
@DavidArno 

> I think it a great shame that the team seem unwilling to even discuss the idea of non-zero default values, including non-null default references. […] This solution would solve **all** of the issues being discussed here in one stroke.

I think that most types do not have a natural default value. What do you propose should be used for those? [The null object pattern](https://en.wikipedia.org/wiki/Null_Object_pattern)?

**Comment by DavidArno** [comment]
@svick,

I think the various ideas around non-zero defaults are contained in the marathon discussion in [Champion "Allow no-arg constructor and field initializers in struct declarations"](https://github.com/dotnet/csharplang/issues/99) and in [Proposal: Overridable `default` operator](https://github.com/dotnet/csharplang/issues/167).

Effectively the idea is that if a type (class or struct), `T`, declares:
```cs
public operator default()
{
    // field initializers
}
```
Then some combination of the compiler, JIT and app startup generates a bit pattern that represents that default state. When `default(T)` is invoked (eg, via `new T[10];`), then rather than zero-filling that memory, the bit pattern is blitted into that memory instead.

For structs, the bit pattern of the default value is used directly. For classes, a singleton instance is created at startup using the bit pattern (or running the operator) and its address is blitted instead.

Of course there are issues with this. Any class used like this would have to be provably immutable, as its a singleton, or a new instance would have to be created with each `default`, causing performance issues. Also, there would potentially be performance issues with address lookups etc.

These issues might be insurmountable, but there are any number of folk more clever than me by far that might come up with solutions.

**Comment by bondsbw** [comment]
@svick If considering `default(T!)` from my [comment above](#issuecomment-322328143), then it would need the constraint `T : new()` and produce the object by calling the default constructor.

**Comment by sharwell** [comment]
> Of course there are issues with this. 

The main issue being it has all the downsides of other uninitialized values (e.g. `null`), but breaks static analysis meant to detect these problems at compile time. Another way to look at this is there is an isomorphism between the current behavior of `default(T)` and the behavior you are proposing, but all optimizations are based on this specific form. By using the current default in place of some other default, you get all the compile-time benefits of a customized `default` operator, plus additional performance benefits at runtime.

**Comment by DavidArno** [comment]
> edit based on comment added by @DavidArno

I really like the idea that `C<T!>` is a contract that translates to `C<T> :  new()` and commits `C` to only using `new`, not `default`. Not sure how I got any sort of credit for this though! 🙃

**Comment by bondsbw** [comment]
@DavidArno Where did `C` come from?  My intention wasn't really to translate into a contract.

Only that the expression `default(T!)` would result in a compile-time error, unless `T` implements a default constructor or the `default` operator.

(Perhaps we would then need a new generic constraint `T : default` that says _`T` must implement the `default` operator_.)

**Comment by DavidArno** [comment]
> @DavidArno Where did `C` come from? My intention wasn't really to translate into such a contract.

It came from the warped innards of my brain. Your `default(T!)` idea went in and that idea popped out! 😀

**Comment by CyrusNajmabadi** [comment]
> And protecting against null is exactly the point of this feature.

It really isn't.  It's preventing against accessing uninitialized state.  Null is totally fine and appropriate in many cases.  Just consider something like a lazy initializer.  

In fact nulls are *great* because they exactly allow static analysis to do it's job and tell you when you're doing something *wrong* (like accessing something uninitialized).  If you get rid of nulls, now you have an issue where you don't get null-refs, but you also just transfer the problem to something else (accessing your values that represent uninitialized state). 

What we want to do is get to a world where you can use nulls in a *much safer fashion*.  

If you don't want nulls today, it's simple, just make every single one of your values an ```Option<T>``` type, or require it to be assigned at construction, and disallow the usage of the null literal.  You could whip up an analyzer to do that sort of thing trivially.

**Comment by eyalsk** [comment]
@CyrusNajmabadi 

> If you don't want nulls today, it's simple, just make every single one of your values an Option<T> type

Well, there are few issues with `Option<T>` today, you need to be dependent on a type that isn't part of the framework or standard so you need to be dependent on a library or write your own, the language doesn't provide any support for it so consuming it is too punishing or/and unpleasant and on top of that wrapping the types with this won't be detected by the kind of flow analysis you do , right? so people would have to do something like this `Option<object>()!` to silence the compiler about it.

**Comment by CyrusNajmabadi** [comment]
@eyalsk Yup.  That was my point.  This is why we're embracing null and making analysis of it baked into the core language.  Again, the point is not to avoid nulls.  The point is to make nulls not problematic.

**Comment by DavidArno** [comment]
It remains the case that the only proven way to "make nulls non problematic" is to make it hard to have `null` occur, ie avoid nulls. 

This feature will help, as it creates a "shallow depression of success" by requiring some syntactic ceremony around not avoiding `null`. However, using options remains the better way. You compare this feature to F#, yet the latter achieves its `null` avoidance by offering good support for options.

As @eyalsk says, the lack of direct support for DU's in the CLR, the lack of `Option<T>` in the framework and the lack of fully featured pattern matching in C#  mean that using options will remain a niche activity amongst C# developers. But times are changing and maybe by C# 9, we really will be able to compare C#'s "mak[ing] nulls not problematic" abilities with F#.

**Comment by yaakov-h** [comment]
@DavidArno `Option<T>` or `modreq` would be the ideal way to go, but it comes at the complete cost of any backwards compatibility. You can only really do something like that if you're starting over from scratch, a la Swift.

**Comment by jnm2** [comment]
> You compare this feature to F#, yet the latter achieves its null avoidance by offering good support for options.

Every time you say this, I do not understand. What earthy difference is there between null and `Option<>.None`? How is one supposed to be less bug prone than the other? The only thing I can see today is that `Option<>` communicates intent in a world where there are few ways to communicate whether a reference typed thing is allowed to be null (which is directly addressed here, yay!). Other than that it's just overhead, no? Few helper methods?

**Comment by bondsbw** [comment]
One issue with `null` is its definition.  What does it mean?

Does `null` in the context of `bool?` mean that it is uninitialized?  That the user has chosen not to answer?  That neither of the answers `true` or `false` are adequate?

`Option<'a>` doesn't solve this problem much better than `null`.  It would be best to build a proper data type:
```f#
type UserOption<'a> =
    | Valid of 'a
    | Uninitialized
    | NoAnswer
    | Inadequate
```

**Comment by DavidArno** [comment]
@jnm2,

Due to the amount of support for testing, eg through pattern matching, for `null` in C#, the differences are actually small and subtle. For example, I can use `int?` as a union of `null` and `int`:
```cs
int? x = SomeSourceOfNullableInt();
Console.WriteLine(x is int y ? $"It's an int: {y}" : "Nothing found"); 
```

So with the nullable reference types feature, we basically get an option union (or maybe monad, if you prefer) of the form `T?`. However, compared with a real `Option<T>`, it's an unreliable monad, for two reasons:
1. Whilst `T?` guarantees that we can get `null` or a value, there is no equivalent guarantee for `T`; it can still be  `null` or a value,
2. Because of this, we get the situation where `null` might mean `none`, or it might be a value.

The following code shows this in action, even with this proposed feature:
```cs
List<string> Foo() => new List<string> {null!};
var first = Foo().FirstOrDefault();
Console.WriteLine(first is string s ? $"First element is {s}" : "list empty");
```
Despite the list containing `null`, our pattern match will claim it's empty.

Unless things changed dramatically, such that `string` were guaranteed to never be `null` (which isn't going to happen), using `string?` as an `Option<string>` and using `string` as a guaranteed value will always be fraught with bug risks.

These same problems do not occur with `Option<T>`. That type is free of the above problems. It just has it's own problems, such as not existing in the framework.

**Comment by jnm2** [comment]
@bondsbw And tracking Uninitialized vs NoAnswer vs Inadequate is irrelevant in about every domain I've seen anyway. Most things just don't need to know the difference.

**Comment by DavidArno** [comment]
@bondsbw,

Please, no! There lies a route to a madness more horrifying than handling the differences between `null` and `undefined` in JavaScript. 😱

**Comment by bondsbw** [comment]
@jnm2 I edited my comment. It was intended to be domain-specific.

You shouldn't use my 'UserOption' any more than you should use 'Option', if it doesn't fit your problem domain.

**Comment by svick** [comment]
@DavidArno

> There lies a route to a madness more horrifying than handling the differences between `null` and `undefined` in JavaScript. 😱

Isn't `Option<T>` like that too? It doesn't get rid of `null`, but it mean you have to handle the differences between `null` and `None`.

**Comment by Joe4evr** [comment]
> Does `null` in the context of `bool?` mean that it is uninitialized? That the user has chosen not to answer? That neither of the answers `true` or `false` are adequate?

[Eric Lippert made a wonderful post about this exact question.](https://ericlippert.com/2012/03/26/null-is-not-false-part-one/)

**Comment by jnm2** [comment]
@DavidArno 

> Despite the list containing null, our pattern match will claim it's empty.

If you're talking about our current definition of `FirstOrDefault`, that's because our current definition of `FirstOrDefault` purposely conflates list-empty and first-item-null... it's in the name... it's not a deficiency of nullable reference vs `Option<>`.

**Comment by bondsbw** [comment]
@DavidArno The problem in JS is, again, you're talking about `null`.  It has no clear definition, so its use is inconsistent and may overlap with usage of `undefined` and certainly has different definitions based on problem domain.

**Comment by orthoxerox** [comment]
@svick you cannot instantiate an `Option<T>` that contains a `null` value. You can use reflection to place one there, but that's dark wizardry outside the realm of propriety, like `unsafePerformIO` is Haskell.

**Comment by DavidArno** [comment]
@svick,

> Isn't `Option<T>` like that too? It doesn't get rid of `null`, but it means you have to handle the differences between `null` and `None`.

Only if `Option<T>` is a class, which is why most libraries that offer an `Option<T>` implement it as a `struct`.

@jnm2,
> If you're talking about our current definition of `FirstOrDefault`...

`FirstOrDefault` is purely an example. The problem is that `null` can mean both a value and no value. That is the problem that this feature partially fixes and `Option<T>` totally fixes.

**Comment by jnm2** [comment]
@DavidArno 

> The problem is that null can mean both a value and no value.

When does null mean a value?

**Comment by bondsbw** [comment]
@jnm2 When lazy developers (myself included) use it to mean things like "Other".

**Comment by jnm2** [comment]
@bondsbw When you use it to mean "other," how is that different than using it to mean "no value"?

**Comment by bondsbw** [comment]
Using it for "other" means that the options provided are not adequate to express my intent, and perhaps it is coupled with an additional text response.  "No value" might mean that the user simply hasn't selected an option.

But what happens when `null` is used?  Someone could later query my data and assume the opposite intent.  Or what if I intend it to have an overloaded meaning, where `null` means "other" when coupled with the text but "no value selected" otherwise?

When I fail to adequately communicate intent in my data types, I've failed to create proper data types.

**Comment by jnm2** [comment]
@bondsbw I agree with all of that about communication, and yet like you said `Option<>.None` has nothing to over over `null` here. However I disagree that it's terrible to use null. In (almost) every domain I've been in, the meaning of null is clear from the context. Wherever the value is consumed it doesn't matter _why_ there is no value. It only matters only _whether_ there is a value.

I wonder if some of that is because people try to conflate their data, domain and UI models. There are other good reasons not to do that. But that kind of whole-model conflation is the only scenario in which I can imagine assumptions being made about what caused the `null`, beyond the simple fact that the value is not present.

**Comment by bondsbw** [comment]
What belongs where is certainly a design decision, with no one-size-fits-all solution.

In the domains I have worked in, I find that storing as much information as possible to be the best case.  I may never use that extra information, but I don't know what I'm going to want to do with it 5 years down the road.  I may need to run usage analytics or investigate a situation.  In my domains, storage is too cheap to throw away any data, even if I don't yet know what I'll do with it.

**Comment by jnm2** [comment]
Certainly a good policy.

**Comment by gulshan** [comment]
What I would propose is-

1) Let us stop calling the feature "Non-nullable reference type" as there is no separate type for nullable/non-nullable references. Just call it "Nullable and non-nullable references" - types not mentioned.
2) And this feature can just be enabled for API endpoints, ie parameter types and return type of methods. For other cases like type-members or local variables, there should be no warning regarding nullability. There can still be "lightbulb" suggestions regarding nullability checking.
3) Literal `null` can have a type of it's own, which is also `null`. Thus the implicit and explicit literal nulls will have separate types. This will make the checking easier in my opinion.

I would insist for the 2nd point only. Other two are just suggestions.

**Comment by Joe4evr** [comment]
> Let us stop calling the feature "Non-nullable reference type"

That's already the case, the feature is called (confusingly, but due to the history of how the feature was developed) "**Nullable** Reference Types".

**Comment by gulshan** [comment]
@Joe4evr My objection is about the "**type**" part, not nullable/non-nullable part. As I have stated- "Nullable and non-nullable references" (no type).

**Comment by RandyBuchholz** [comment]
Re: What is null? and Reference Type vs Reference - my 2C.
I think `bool?` is a good staring point for asking what null is, especially if we drop down into hardware implementations. TTL chips implement `bool?` using tri-state logic. The "states" are high ( true/plus/5V/etc.), low (false/zero/0V/etc.), and high-impedance (null). This is misleading, because is sounds like the `bool` has three states itself. But high-impedance isn't a state of the Boolean, it is the state of our ability to evaluate the Boolean - in this context null means "unevaluable". Most nullables (except for things like bool) can have a value or not, but it doesn't matter, because as long as it is in the null state it can't be evaluated. A `bool` can only be true or false. The construct `bool?` should not create a new special type that can have no value -it really means we have a regular `bool` (true or false) but at this point in time we cannot evaluate it - evaluation is impeded. Null ~= none. But not it is not the value that is "none", but the thing that contains the value is the "none". In software though, nulls are implemented more as "optionally valued" objects and less as true null items.   

Should it be Null Reference or Null Reference Type? It's like Schrödinger's cat. The cat is null when the box is closed - unevaluable. But it has a type (Cat) and values - color, alive/dead, etc. They are just clocked from us. When we open the box we will see a dead cat or an alive cat, but still a cat. It's the same with objects in memory. If we create a reference object it has a type with memory allocation for that type, and a pointer to the base. If we make that null, we don't necessarily destroy the object, we remove the ability to resolve the pointer. The Reference Type isn't about the "type", it's about the reference - (Pointer _Reference_ to the base location of a _Type_ Instance). In this case, we expect the pointer to point to the base location of memory that can be read as a Cat. Dropping 'Type' would translate to Pointer Referencing a Memory Location (Non-Nullable Reference) or Pointer Possibly Referencing a Memory Location (Nullable Reference). We have no idea what we might find at that location.

Since nullable isn't about the object itself, but our ability to evaluate the object, default values are something of a requirement - but really only in the case of bool. Booleans can only be true or false by definition. If we allow conversion between nullable and non-nullable, that means when we "de-cloak" a bool it must have a value. Value types like `int` can naturally have no value - zero isn't a "natural" default. There are two related and confused items here - "unknown" and null. Essentially, null means we can't resolve the pointer - it is in the high-impedance state. Unknown means we can resolve the pointer, but can't resolve what it points to. From a programmer perspective though, there isn't a lot of apparent difference, though one would be a true null reference and the other technically an invalid cast. I imagine that is part of why value types like int have default values. We need a way to check if we have a "null" or an "unknown", which kind of gets us back into the null-check world. A good option is to require that a non-nullable type have a default. But how is that defined? A Delphi-like Metatype? Probably a great approach but also a lot of change. I know there is a proposal somewhere for that, just can't find it...

It seems to me that what we are really after is "Mandatory Valued Objects" as much as a true not-null - we want to ensure that our references point to locations that have "resolvable" objects, not that they just point to a location that can have a object.

**Comment by sharwell** [comment]
@RandyBuchholz I'm not sure what you are agreeing with / disagreeing with / proposing. It seems like that is mostly an argument in favor of renaming the feature from "Nullable reference types" to just "Nullable references", but other than that can you clarify the specific desired outcomes?

**Comment by RandyBuchholz** [comment]
@sharwell Sorry, kind of rambling. I was jumping in on the conversation about what null is and if it can have values, and comments about dropping type from the name. It seems like "null" is often considered  a special value (enforced by being able to do `x = null`). But null isn't a value, it's closer to a location or visibility.  It's the ability to determine the value. So you wouldn't say "the value of x is null", you would say " x is null".

So when we talk about different aspects/attributes of "nullable" that may be a perspective to consider. Some languages do that to different degrees, which is why we have null, none, undefined appearing together. That leads to my last comment about what we want isn't really tied to the definition of null. What we want is to be able to constrain objects (in this case reference objects) to always have a value, and to always be able to determine that value. 

I'm disagreeing about dropping type. I think "Nullable Reference Type" is better than "Nullable Reference". But really (I'm not proposing this) "Mandatory" or "Required" would more accurately describe what we want.

I don't have a complete proposal for a desired outcome, other than not changing the direction things are going right now. But a general outcome I would like to see (and have been working on a proposal for) is something along the lines of a "Domain" concept in the language. Not in the DDD way but in the UDT or database way. This isn't a syntax I would use, but just for the general idea - `Domain PersonName string len:8-24 required, rules {...}`  

```
class Person {
  public PersonName FirstName { get; set; }
}
```
